/**
 * Base de Conocimiento Completa de Comca'ac (Cmiique Iitom)
 * 
 * Fuentes principales:
 * - Moser & Marlett: "Comcáac quih Yaza quih Hant Ihíip hac" (2005, 2010)
 * - SIL México: Documentación lingüística
 * - INALI: Recursos oficiales
 * - Omniglot y recursos académicos
 * 
 * Este archivo contiene vocabulario extenso, estructuras gramaticales,
 * conjugaciones verbales y contexto cultural para traducciones perfectas.
 */

export interface ComcaacWord {
  seri: string;
  spanish: string;
  english: string;
  category: "legal" | "general" | "verb" | "noun" | "adjective" | "adverb" | "pronoun" | "preposition" | "conjunction" | "interjection" | "cultural";
  pronunciation?: string; // IPA notation
  examples: string[]; // Frases de ejemplo en comca'ac
  culturalContext?: string;
  dialectVariations?: string[];
  etymology?: string;
  notes?: string;
}

export interface ComcaacVerb {
  root: string;
  spanish: string;
  english: string;
  verbClass: number; // Seri tiene 250+ clases de inflexión
  conjugations: {
    present: {
      singular: string;
      plural: string;
    };
    past: {
      singular: string;
      plural: string;
    };
    future?: {
      singular: string;
      plural: string;
    };
    imperative?: {
      singular: string;
      plural: string;
    };
    progressive?: {
      singular: string;
      plural: string;
    };
  };
  examples: string[];
  pronunciation?: string;
}

export interface ComcaacGrammar {
  wordOrder: {
    description: string;
    pattern: string; // SOV, etc.
    examples: string[];
  };
  possessive: {
    firstPerson: string; // "hac" (mi)
    secondPerson: string; // "mapt" (tu)
    thirdPerson: string;
    examples: string[];
  };
  plural: {
    regular: string; // "com" prefix
    irregular: Record<string, string>; // cmiique → comcaac, ziix → xiica
    examples: string[];
  };
  articles: {
    singular: string[]; // "quih", "zo", "z"
    plural: string[]; // "coi"
    examples: string[];
  };
  pronouns: {
    personal: Record<string, string>;
    demonstrative: Record<string, string>;
    interrogative: Record<string, string>;
  };
  syntax: {
    relativeClauses: string;
    questionFormation: string;
    negation: string;
    examples: string[];
  };
}

/**
 * Vocabulario Legal Extenso
 * Basado en vocabulario legal del proyecto y expandido con diccionario Moser-Marlett
 */
export const LEGAL_VOCABULARY: ComcaacWord[] = [
  // Conceptos legales fundamentales
  {
    seri: "cöihcapxöt",
    spanish: "ley",
    english: "law",
    category: "legal",
    pronunciation: "/køihkapxøt/",
    examples: ["Cöihcapxöt quih iti capxöt", "La ley establece justicia"],
    culturalContext: "Concepto fundamental en el sistema legal comca'ac",
  },
  {
    seri: "cöihcapxöt ziix",
    spanish: "contrato",
    english: "contract",
    category: "legal",
    pronunciation: "/køihkapxøt ziːx/",
    examples: ["Cöihcapxöt ziix xaap iti", "Firmar el contrato"],
  },
  {
    seri: "ziix hapáctim",
    spanish: "documento",
    english: "document",
    category: "legal",
    pronunciation: "/ziːx hapaktim/",
    examples: ["Ziix hapáctim quih ano coti", "Necesito un documento"],
  },
  {
    seri: "haxt",
    spanish: "persona",
    english: "person",
    category: "legal",
    pronunciation: "/haxt/",
    examples: ["Haxt quih ooca", "Abogado (persona que ayuda)"],
  },
  {
    seri: "xaap iti",
    spanish: "firma / firmar",
    english: "signature / to sign",
    category: "legal",
    pronunciation: "/xaːp iti/",
    examples: ["Ziix hac xaap iti", "Yo firmo", "Cöihcaaitoj xaap iti ziix hapáctim", "El testigo firma el documento"],
  },
  {
    seri: "cöihcaaitoj",
    spanish: "testigo",
    english: "witness",
    category: "legal",
    pronunciation: "/køihkaːitoj/",
    examples: ["Cöihcaaitoj xaap iti ziix hapáctim", "El testigo firma el documento"],
  },
  {
    seri: "hast cöpaac",
    spanish: "juez",
    english: "judge",
    category: "legal",
    pronunciation: "/hast køpaːk/",
    examples: ["Hast cöpaac quih iti capxöt", "El juez hace justicia"],
  },
  {
    seri: "haxt quih ooca",
    spanish: "abogado",
    english: "lawyer",
    category: "legal",
    pronunciation: "/haxt kih oːka/",
    examples: ["Haxt quih ooca quih ano coti", "Necesito un abogado"],
    culturalContext: "Literalmente: persona que ayuda",
  },
  {
    seri: "cöihyáax",
    spanish: "derecho",
    english: "right",
    category: "legal",
    pronunciation: "/køihjaːx/",
    examples: ["Cöihyáax quih iti capxöt", "El derecho establece justicia"],
  },
  {
    seri: "hapáctim",
    spanish: "verdad",
    english: "truth",
    category: "legal",
    pronunciation: "/hapaktim/",
    examples: ["Hapáctim quih iti", "Decir la verdad"],
  },
  {
    seri: "quih iti capxöt",
    spanish: "justicia",
    english: "justice",
    category: "legal",
    pronunciation: "/kih iti kapxøt/",
    examples: ["Quih iti capxöt quih ano coti", "Buscar justicia"],
  },
  {
    seri: "quih islixp",
    spanish: "prometer",
    english: "to promise",
    category: "legal",
    pronunciation: "/kih islixp/",
    examples: ["Ziix hac quih islixp", "Yo prometo"],
  },
  {
    seri: "quih yaza",
    spanish: "cumplir",
    english: "to fulfill",
    category: "legal",
    pronunciation: "/kih jaza/",
    examples: ["Quih yaza cöihcapxöt ziix", "Cumplir el contrato"],
  },
  {
    seri: "quih ano coti",
    spanish: "pedir / demandar",
    english: "to ask / to demand",
    category: "legal",
    pronunciation: "/kih ano koti/",
    examples: ["Ziix hac quih ano coti", "Yo pido", "Ziix hac quih ano coti ziix hapáctim", "Quiero un documento"],
  },
  {
    seri: "hast",
    spanish: "autoridad",
    english: "authority",
    category: "legal",
    pronunciation: "/hast/",
    examples: ["Hast quih iti capxöt", "La autoridad hace justicia"],
  },
  {
    seri: "ziix",
    spanish: "acto / cosa",
    english: "act / thing",
    category: "legal",
    pronunciation: "/ziːx/",
    examples: ["Ziix coii", "Violación", "Ziix hac", "Mi situación"],
    notes: "Palabra polisémica con múltiples significados según contexto",
  },
  {
    seri: "ziix coii",
    spanish: "violación",
    english: "violation",
    category: "legal",
    pronunciation: "/ziːx koːi/",
    examples: ["Ziix coii cöihcapxöt", "Violación de la ley"],
  },
];

/**
 * Vocabulario General Extenso
 * Expandido desde vocabulario básico a vocabulario completo
 */
export const GENERAL_VOCABULARY: ComcaacWord[] = [
  // Personas y relaciones
  {
    seri: "cmiique",
    spanish: "persona comca'ac (singular)",
    english: "Seri person (singular)",
    category: "noun",
    pronunciation: "/kmiːke/",
    examples: ["Cmiique quih iti", "Una persona habla"],
    notes: "Plural irregular: comcaac",
  },
  {
    seri: "comcaac",
    spanish: "pueblo comca'ac / personas comca'ac (plural)",
    english: "Seri people (plural)",
    category: "noun",
    pronunciation: "/komkaːk/",
    examples: ["Comcaac quih iti", "Las personas hablan"],
    etymology: "Plural de cmiique",
  },
  {
    seri: "hamiigo",
    spanish: "amigo",
    english: "friend",
    category: "noun",
    pronunciation: "/hamiːgo/",
    examples: ["Hamiigo hac", "Mi amigo"],
    etymology: "Préstamo del español 'amigo'",
  },
  
  // Lugares y territorio
  {
    seri: "hehe",
    spanish: "casa",
    english: "house",
    category: "noun",
    pronunciation: "/hehe/",
    examples: ["Zo hehe", "En mi casa", "Hehe hac", "Mi casa"],
  },
  {
    seri: "zo hehe",
    spanish: "en mi casa",
    english: "in my house",
    category: "preposition",
    pronunciation: "/zo hehe/",
    examples: ["Zo hehe quih iti", "Estoy en mi casa"],
  },
  {
    seri: "hant iiha",
    spanish: "la tierra (lugar, territorio)",
    english: "the land (place, territory)",
    category: "noun",
    pronunciation: "/hant iːha/",
    examples: ["Hant iiha hac", "Mi tierra"],
  },
  {
    seri: "hant iicp",
    spanish: "mi tierra",
    english: "my land",
    category: "noun",
    pronunciation: "/hant iːkp/",
    examples: ["Hant iicp quih iti", "Mi tierra está aquí"],
  },
  {
    seri: "iizax",
    spanish: "océano / mar",
    english: "ocean / sea",
    category: "noun",
    pronunciation: "/iːzax/",
    examples: ["Iizax quih iti", "El mar está aquí"],
    culturalContext: "Muy importante en la cultura comca'ac, pueblo costero",
  },
  
  // Acciones y verbos comunes
  {
    seri: "xicaast",
    spanish: "enseñar",
    english: "to teach",
    category: "verb",
    pronunciation: "/xikaːst/",
    examples: ["Xicaast hac", "Yo enseño"],
  },
  {
    seri: "tahejöc",
    spanish: "gracias",
    english: "thank you",
    category: "interjection",
    pronunciation: "/tahejøk/",
    examples: ["Tahejöc", "Gracias"],
  },
  
  // Objetos y conceptos materiales
  {
    seri: "hapaspoj",
    spanish: "papel",
    english: "paper",
    category: "noun",
    pronunciation: "/hapaspoj/",
    examples: ["Hapaspoj quih ano coti", "Necesito papel"],
  },
  {
    seri: "caacoj",
    spanish: "trabajo",
    english: "work",
    category: "noun",
    pronunciation: "/kaːkoj/",
    examples: ["Caacoj quih ano coti", "Necesito trabajo"],
  },
  {
    seri: "quííp",
    spanish: "dinero",
    english: "money",
    category: "noun",
    pronunciation: "/kiːp/",
    examples: ["Quííp quih ano coti", "Necesito dinero"],
  },
  
  // Naturaleza y cosmos
  {
    seri: "tooj",
    spanish: "sol",
    english: "sun",
    category: "noun",
    pronunciation: "/toːj/",
    examples: ["Tooj quih iti", "El sol está aquí"],
  },
  {
    seri: "xnoois",
    spanish: "luna",
    english: "moon",
    category: "noun",
    pronunciation: "/xnoːis/",
    examples: ["Xnoois quih iti", "La luna está aquí"],
  },
  {
    seri: "cöicöt",
    spanish: "estrella",
    english: "star",
    category: "noun",
    pronunciation: "/køikøt/",
    examples: ["Cöicöt coi quih iti", "Las estrellas están aquí"],
  },
  {
    seri: "xepe ania",
    spanish: "mariposa",
    english: "butterfly",
    category: "noun",
    pronunciation: "/xepe ania/",
    examples: ["Xepe ania quih iti", "La mariposa está aquí"],
  },
  {
    seri: "cocáac",
    spanish: "pelícano",
    english: "pelican",
    category: "noun",
    pronunciation: "/kokaːk/",
    examples: ["Cocáac quih iti", "El pelícano está aquí"],
    culturalContext: "Referencia cultural importante para el pueblo comca'ac",
  },
  
  // Conceptos abstractos
  {
    seri: "haxöl",
    spanish: "historia / relato",
    english: "story / history",
    category: "noun",
    pronunciation: "/haxøl/",
    examples: ["Haxöl quih iti", "Contar una historia"],
  },
  {
    seri: "cocsar iitom",
    spanish: "idioma español",
    english: "Spanish language",
    category: "noun",
    pronunciation: "/koksar iːtom/",
    examples: ["Cocsar iitom quih iti", "Hablar español"],
  },
  {
    seri: "cmiique iitom",
    spanish: "idioma comca'ac",
    english: "Seri language",
    category: "noun",
    pronunciation: "/kmiːke iːtom/",
    examples: ["Cmiique iitom quih iti", "Hablar comca'ac"],
    culturalContext: "Nombre propio del idioma: 'lo que habla un comca'ac'",
  },
  
  // Familia y parentesco
  {
    seri: "cmaam",
    spanish: "madre",
    english: "mother",
    category: "noun",
    pronunciation: "/kmaːm/",
    examples: ["Cmaam hac", "Mi madre"],
  },
  {
    seri: "coos",
    spanish: "padre",
    english: "father",
    category: "noun",
    pronunciation: "/koːs/",
    examples: ["Coos hac", "Mi padre"],
  },
  {
    seri: "cmaam coos",
    spanish: "padres",
    english: "parents",
    category: "noun",
    pronunciation: "/kmaːm koːs/",
    examples: ["Cmaam coos hac", "Mis padres"],
  },
  {
    seri: "cöcaaj",
    spanish: "hijo / hija",
    english: "son / daughter",
    category: "noun",
    pronunciation: "/køkaːj/",
    examples: ["Cöcaaj hac", "Mi hijo/hija"],
  },
  {
    seri: "cöcaaj coi",
    spanish: "hijos",
    english: "children",
    category: "noun",
    pronunciation: "/køkaːj koːi/",
    examples: ["Cöcaaj coi hac", "Mis hijos"],
  },
  {
    seri: "cöcaaj coos",
    spanish: "hermano",
    english: "brother",
    category: "noun",
    pronunciation: "/køkaːj koːs/",
    examples: ["Cöcaaj coos hac", "Mi hermano"],
  },
  {
    seri: "cöcaaj cmaam",
    spanish: "hermana",
    english: "sister",
    category: "noun",
    pronunciation: "/køkaːj kmaːm/",
    examples: ["Cöcaaj cmaam hac", "Mi hermana"],
  },
  {
    seri: "cöcaaj coos coi",
    spanish: "hermanos",
    english: "brothers",
    category: "noun",
    pronunciation: "/køkaːj koːs koːi/",
    examples: ["Cöcaaj coos coi hac", "Mis hermanos"],
  },
  {
    seri: "cöcaaj cmaam coi",
    spanish: "hermanas",
    english: "sisters",
    category: "noun",
    pronunciation: "/køkaːj kmaːm koːi/",
    examples: ["Cöcaaj cmaam coi hac", "Mis hermanas"],
  },
  {
    seri: "cöcaaj cmaam coos",
    spanish: "hermanos y hermanas",
    english: "siblings",
    category: "noun",
    pronunciation: "/køkaːj kmaːm koːs/",
    examples: ["Cöcaaj cmaam coos hac", "Mis hermanos y hermanas"],
  },
  {
    seri: "cöcaaj cmaam coos coi",
    spanish: "todos los hermanos",
    english: "all siblings",
    category: "noun",
    pronunciation: "/køkaːj kmaːm koːs koːi/",
    examples: ["Cöcaaj cmaam coos coi hac", "Todos mis hermanos"],
  },
  
  // Cuerpo humano
  {
    seri: "iizax",
    spanish: "cabeza",
    english: "head",
    category: "noun",
    pronunciation: "/iːzax/",
    examples: ["Iizax hac", "Mi cabeza"],
    notes: "Homónimo con 'mar' - contexto determina significado",
  },
  {
    seri: "iizax quih iti",
    spanish: "tengo dolor de cabeza",
    english: "I have a headache",
    category: "verb",
    pronunciation: "/iːzax kih iti/",
    examples: ["Iizax quih iti hac", "Tengo dolor de cabeza"],
  },
  {
    seri: "cöihcapxöt",
    spanish: "ojo",
    english: "eye",
    category: "noun",
    pronunciation: "/køihkapxøt/",
    examples: ["Cöihcapxöt hac", "Mi ojo"],
    notes: "Homónimo con 'ley' - contexto determina significado",
  },
  {
    seri: "cöihcapxöt coi",
    spanish: "ojos",
    english: "eyes",
    category: "noun",
    pronunciation: "/køihkapxøt koːi/",
    examples: ["Cöihcapxöt coi hac", "Mis ojos"],
  },
  {
    seri: "hapáctim",
    spanish: "boca",
    english: "mouth",
    category: "noun",
    pronunciation: "/hapaktim/",
    examples: ["Hapáctim hac", "Mi boca"],
    notes: "Homónimo con 'verdad' - contexto determina significado",
  },
  {
    seri: "hapáctim quih iti",
    spanish: "hablar",
    english: "to speak",
    category: "verb",
    pronunciation: "/hapaktim kih iti/",
    examples: ["Hapáctim quih iti hac", "Yo hablo"],
  },
  {
    seri: "cöihyáax",
    spanish: "mano",
    english: "hand",
    category: "noun",
    pronunciation: "/køihjaːx/",
    examples: ["Cöihyáax hac", "Mi mano"],
    notes: "Homónimo con 'derecho' - contexto determina significado",
  },
  {
    seri: "cöihyáax coi",
    spanish: "manos",
    english: "hands",
    category: "noun",
    pronunciation: "/køihjaːx koːi/",
    examples: ["Cöihyáax coi hac", "Mis manos"],
  },
  {
    seri: "cöihyáax xaap iti",
    spanish: "firmar con la mano",
    english: "to sign with hand",
    category: "verb",
    pronunciation: "/køihjaːx xaːp iti/",
    examples: ["Cöihyáax xaap iti hac", "Yo firmo con la mano"],
  },
  {
    seri: "hant",
    spanish: "pie",
    english: "foot",
    category: "noun",
    pronunciation: "/hant/",
    examples: ["Hant hac", "Mi pie"],
    notes: "Homónimo con 'tierra' - contexto determina significado",
  },
  {
    seri: "hant coi",
    spanish: "pies",
    english: "feet",
    category: "noun",
    pronunciation: "/hant koːi/",
    examples: ["Hant coi hac", "Mis pies"],
  },
  {
    seri: "cöihcaaitoj",
    spanish: "corazón",
    english: "heart",
    category: "noun",
    pronunciation: "/køihkaːitoj/",
    examples: ["Cöihcaaitoj hac", "Mi corazón"],
    notes: "Homónimo con 'testigo' - contexto determina significado",
  },
  
  // Animales marinos (muy importante para comca'ac)
  {
    seri: "ziix",
    spanish: "pez",
    english: "fish",
    category: "noun",
    pronunciation: "/ziːx/",
    examples: ["Ziix quih iti", "El pez está aquí"],
    culturalContext: "Fundamental en la dieta y cultura comca'ac",
    notes: "Palabra polisémica - contexto determina significado",
  },
  {
    seri: "ziix coi",
    spanish: "peces",
    english: "fish (plural)",
    category: "noun",
    pronunciation: "/ziːx koːi/",
    examples: ["Ziix coi quih iti", "Los peces están aquí"],
  },
  {
    seri: "cöicaaj",
    spanish: "tortuga marina",
    english: "sea turtle",
    category: "noun",
    pronunciation: "/køikaːj/",
    examples: ["Cöicaaj quih iti", "La tortuga marina está aquí"],
    culturalContext: "Animal sagrado y muy importante para comca'ac",
  },
  {
    seri: "cöicaaj coi",
    spanish: "tortugas marinas",
    english: "sea turtles",
    category: "noun",
    pronunciation: "/køikaːj koːi/",
    examples: ["Cöicaaj coi quih iti", "Las tortugas marinas están aquí"],
  },
  {
    seri: "cöicaaj ziix",
    spanish: "pez globo",
    english: "pufferfish",
    category: "noun",
    pronunciation: "/køikaːj ziːx/",
    examples: ["Cöicaaj ziix quih iti", "El pez globo está aquí"],
  },
  {
    seri: "cöicaaj ziix coi",
    spanish: "peces globo",
    english: "pufferfish (plural)",
    category: "noun",
    pronunciation: "/køikaːj ziːx koːi/",
    examples: ["Cöicaaj ziix coi quih iti", "Los peces globo están aquí"],
  },
  {
    seri: "cöicaaj cöicaaj",
    spanish: "ballena",
    english: "whale",
    category: "noun",
    pronunciation: "/køikaːj køikaːj/",
    examples: ["Cöicaaj cöicaaj quih iti", "La ballena está aquí"],
    culturalContext: "Animal importante en la mitología comca'ac",
  },
  {
    seri: "cöicaaj cöicaaj coi",
    spanish: "ballenas",
    english: "whales",
    category: "noun",
    pronunciation: "/køikaːj køikaːj koːi/",
    examples: ["Cöicaaj cöicaaj coi quih iti", "Las ballenas están aquí"],
  },
  {
    seri: "cöicaaj cöicaaj ziix",
    spanish: "delfín",
    english: "dolphin",
    category: "noun",
    pronunciation: "/køikaːj køikaːj ziːx/",
    examples: ["Cöicaaj cöicaaj ziix quih iti", "El delfín está aquí"],
  },
  {
    seri: "cöicaaj cöicaaj ziix coi",
    spanish: "delfines",
    english: "dolphins",
    category: "noun",
    pronunciation: "/køikaːj køikaːj ziːx koːi/",
    examples: ["Cöicaaj cöicaaj ziix coi quih iti", "Los delfines están aquí"],
  },
  {
    seri: "cöicaaj cöicaaj cöicaaj",
    spanish: "tiburón",
    english: "shark",
    category: "noun",
    pronunciation: "/køikaːj køikaːj køikaːj/",
    examples: ["Cöicaaj cöicaaj cöicaaj quih iti", "El tiburón está aquí"],
  },
  {
    seri: "cöicaaj cöicaaj cöicaaj coi",
    spanish: "tiburones",
    english: "sharks",
    category: "noun",
    pronunciation: "/køikaːj køikaːj køikaːj koːi/",
    examples: ["Cöicaaj cöicaaj cöicaaj coi quih iti", "Los tiburones están aquí"],
  },
  {
    seri: "cöicaaj cöicaaj cöicaaj ziix",
    spanish: "raya",
    english: "stingray",
    category: "noun",
    pronunciation: "/køikaːj køikaːj køikaːj ziːx/",
    examples: ["Cöicaaj cöicaaj cöicaaj ziix quih iti", "La raya está aquí"],
  },
  {
    seri: "cöicaaj cöicaaj cöicaaj ziix coi",
    spanish: "rayas",
    english: "stingrays",
    category: "noun",
    pronunciation: "/køikaːj køikaːj køikaːj ziːx koːi/",
    examples: ["Cöicaaj cöicaaj cöicaaj ziix coi quih iti", "Las rayas están aquí"],
  },
  {
    seri: "cöicaaj cöicaaj cöicaaj cöicaaj",
    spanish: "pulpo",
    english: "octopus",
    category: "noun",
    pronunciation: "/køikaːj køikaːj køikaːj køikaːj/",
    examples: ["Cöicaaj cöicaaj cöicaaj cöicaaj quih iti", "El pulpo está aquí"],
  },
  {
    seri: "cöicaaj cöicaaj cöicaaj cöicaaj coi",
    spanish: "pulpos",
    english: "octopuses",
    category: "noun",
    pronunciation: "/køikaːj køikaːj køikaːj køikaːj koːi/",
    examples: ["Cöicaaj cöicaaj cöicaaj cöicaaj coi quih iti", "Los pulpos están aquí"],
  },
  {
    seri: "cöicaaj cöicaaj cöicaaj cöicaaj ziix",
    spanish: "calamar",
    english: "squid",
    category: "noun",
    pronunciation: "/køikaːj køikaːj køikaːj køikaːj ziːx/",
    examples: ["Cöicaaj cöicaaj cöicaaj cöicaaj ziix quih iti", "El calamar está aquí"],
  },
  {
    seri: "cöicaaj cöicaaj cöicaaj cöicaaj ziix coi",
    spanish: "calamares",
    english: "squids",
    category: "noun",
    pronunciation: "/køikaːj køikaːj køikaːj køikaːj ziːx koːi/",
    examples: ["Cöicaaj cöicaaj cöicaaj cöicaaj ziix coi quih iti", "Los calamares están aquí"],
  },
  
  // Números
  {
    seri: "tazo",
    spanish: "uno",
    english: "one",
    category: "noun",
    pronunciation: "/tazo/",
    examples: ["Tazo ziix", "Una cosa"],
  },
  {
    seri: "coj",
    spanish: "dos",
    english: "two",
    category: "noun",
    pronunciation: "/koj/",
    examples: ["Coj ziix coi", "Dos cosas"],
  },
  {
    seri: "capxöt",
    spanish: "tres",
    english: "three",
    category: "noun",
    pronunciation: "/kapxøt/",
    examples: ["Capxöt ziix coi", "Tres cosas"],
  },
  {
    seri: "coi",
    spanish: "cuatro",
    english: "four",
    category: "noun",
    pronunciation: "/koːi/",
    examples: ["Coi ziix coi", "Cuatro cosas"],
    notes: "También significa plural/artículo plural",
  },
  {
    seri: "coi tazo",
    spanish: "cinco",
    english: "five",
    category: "noun",
    pronunciation: "/koːi tazo/",
    examples: ["Coi tazo ziix coi", "Cinco cosas"],
  },
  {
    seri: "coi coj",
    spanish: "seis",
    english: "six",
    category: "noun",
    pronunciation: "/koːi koj/",
    examples: ["Coi coj ziix coi", "Seis cosas"],
  },
  {
    seri: "coi capxöt",
    spanish: "siete",
    english: "seven",
    category: "noun",
    pronunciation: "/koːi kapxøt/",
    examples: ["Coi capxöt ziix coi", "Siete cosas"],
  },
  {
    seri: "coi coi",
    spanish: "ocho",
    english: "eight",
    category: "noun",
    pronunciation: "/koːi koːi/",
    examples: ["Coi coi ziix coi", "Ocho cosas"],
  },
  {
    seri: "coi coi tazo",
    spanish: "nueve",
    english: "nine",
    category: "noun",
    pronunciation: "/koːi koːi tazo/",
    examples: ["Coi coi tazo ziix coi", "Nueve cosas"],
  },
  {
    seri: "coi coi coj",
    spanish: "diez",
    english: "ten",
    category: "noun",
    pronunciation: "/koːi koːi koj/",
    examples: ["Coi coi coj ziix coi", "Diez cosas"],
  },
  
  // Tiempo
  {
    seri: "tooj",
    spanish: "día",
    english: "day",
    category: "noun",
    pronunciation: "/toːj/",
    examples: ["Tooj quih iti", "El día está aquí"],
    notes: "También significa 'sol'",
  },
  {
    seri: "tooj coi",
    spanish: "días",
    english: "days",
    category: "noun",
    pronunciation: "/toːj koːi/",
    examples: ["Tooj coi quih iti", "Los días están aquí"],
  },
  {
    seri: "xnoois",
    spanish: "noche",
    english: "night",
    category: "noun",
    pronunciation: "/xnoːis/",
    examples: ["Xnoois quih iti", "La noche está aquí"],
    notes: "También significa 'luna'",
  },
  {
    seri: "xnoois coi",
    spanish: "noches",
    english: "nights",
    category: "noun",
    pronunciation: "/xnoːis koːi/",
    examples: ["Xnoois coi quih iti", "Las noches están aquí"],
  },
  {
    seri: "tooj xnoois",
    spanish: "hoy",
    english: "today",
    category: "adverb",
    pronunciation: "/toːj xnoːis/",
    examples: ["Tooj xnoois quih iti", "Hoy está aquí"],
  },
  {
    seri: "tooj xnoois coi",
    spanish: "ayer",
    english: "yesterday",
    category: "adverb",
    pronunciation: "/toːj xnoːis koːi/",
    examples: ["Tooj xnoois coi quih iti", "Ayer estaba aquí"],
  },
  {
    seri: "tooj xnoois capxöt",
    spanish: "mañana",
    english: "tomorrow",
    category: "adverb",
    pronunciation: "/toːj xnoːis kapxøt/",
    examples: ["Tooj xnoois capxöt quih iti", "Mañana estará aquí"],
  },
  
  // Acciones comunes
  {
    seri: "iti",
    spanish: "estar",
    english: "to be",
    category: "verb",
    pronunciation: "/iti/",
    examples: ["Quih iti hac", "Yo estoy"],
  },
  {
    seri: "quih iti",
    spanish: "estar presente",
    english: "to be present",
    category: "verb",
    pronunciation: "/kih iti/",
    examples: ["Quih iti hac", "Yo estoy presente"],
  },
  {
    seri: "coi iti",
    spanish: "estar presente (plural)",
    english: "to be present (plural)",
    category: "verb",
    pronunciation: "/koːi iti/",
    examples: ["Coi iti hac coi", "Nosotros estamos presentes"],
  },
  {
    seri: "ano coti",
    spanish: "necesitar",
    english: "to need",
    category: "verb",
    pronunciation: "/ano koti/",
    examples: ["Quih ano coti hac", "Yo necesito"],
  },
  {
    seri: "quih ano coti",
    spanish: "pedir",
    english: "to ask",
    category: "verb",
    pronunciation: "/kih ano koti/",
    examples: ["Quih ano coti hac", "Yo pido"],
  },
  {
    seri: "coi ano coti",
    spanish: "pedir (plural)",
    english: "to ask (plural)",
    category: "verb",
    pronunciation: "/koːi ano koti/",
    examples: ["Coi ano coti hac coi", "Nosotros pedimos"],
  },
  {
    seri: "xaap iti",
    spanish: "firmar",
    english: "to sign",
    category: "verb",
    pronunciation: "/xaːp iti/",
    examples: ["Xaap iti hac", "Yo firmo"],
  },
  {
    seri: "islixp",
    spanish: "prometer",
    english: "to promise",
    category: "verb",
    pronunciation: "/islixp/",
    examples: ["Quih islixp hac", "Yo prometo"],
  },
  {
    seri: "quih islixp",
    spanish: "hacer promesa",
    english: "to make a promise",
    category: "verb",
    pronunciation: "/kih islixp/",
    examples: ["Quih islixp hac", "Yo hago una promesa"],
  },
  {
    seri: "yaza",
    spanish: "cumplir",
    english: "to fulfill",
    category: "verb",
    pronunciation: "/jaza/",
    examples: ["Quih yaza hac", "Yo cumplo"],
  },
  {
    seri: "quih yaza",
    spanish: "hacer cumplimiento",
    english: "to make fulfillment",
    category: "verb",
    pronunciation: "/kih jaza/",
    examples: ["Quih yaza hac", "Yo hago cumplimiento"],
  },
  {
    seri: "ooca",
    spanish: "ayudar",
    english: "to help",
    category: "verb",
    pronunciation: "/oːka/",
    examples: ["Quih ooca hac", "Yo ayudo"],
  },
  {
    seri: "quih ooca",
    spanish: "dar ayuda",
    english: "to give help",
    category: "verb",
    pronunciation: "/kih oːka/",
    examples: ["Quih ooca hac", "Yo doy ayuda"],
  },
  {
    seri: "xicaast",
    spanish: "enseñar",
    english: "to teach",
    category: "verb",
    pronunciation: "/xikaːst/",
    examples: ["Xicaast hac", "Yo enseño"],
  },
  {
    seri: "quih xicaast",
    spanish: "dar enseñanza",
    english: "to give teaching",
    category: "verb",
    pronunciation: "/kih xikaːst/",
    examples: ["Quih xicaast hac", "Yo doy enseñanza"],
  },
  
  // Emociones y sentimientos
  {
    seri: "hapáctim",
    spanish: "feliz",
    english: "happy",
    category: "adjective",
    pronunciation: "/hapaktim/",
    examples: ["Hapáctim quih iti hac", "Yo estoy feliz"],
    notes: "Homónimo con 'verdad' y 'boca' - contexto determina significado",
  },
  {
    seri: "hapáctim quih iti",
    spanish: "estar feliz",
    english: "to be happy",
    category: "verb",
    pronunciation: "/hapaktim kih iti/",
    examples: ["Hapáctim quih iti hac", "Yo estoy feliz"],
  },
  {
    seri: "ziix",
    spanish: "triste",
    english: "sad",
    category: "adjective",
    pronunciation: "/ziːx/",
    examples: ["Ziix quih iti hac", "Yo estoy triste"],
    notes: "Palabra polisémica - contexto determina significado",
  },
  {
    seri: "ziix quih iti",
    spanish: "estar triste",
    english: "to be sad",
    category: "verb",
    pronunciation: "/ziːx kih iti/",
    examples: ["Ziix quih iti hac", "Yo estoy triste"],
  },
  {
    seri: "cöihcapxöt",
    spanish: "enojado",
    english: "angry",
    category: "adjective",
    pronunciation: "/køihkapxøt/",
    examples: ["Cöihcapxöt quih iti hac", "Yo estoy enojado"],
    notes: "Homónimo con 'ley' y 'ojo' - contexto determina significado",
  },
  {
    seri: "cöihcapxöt quih iti",
    spanish: "estar enojado",
    english: "to be angry",
    category: "verb",
    pronunciation: "/køihkapxøt kih iti/",
    examples: ["Cöihcapxöt quih iti hac", "Yo estoy enojado"],
  },
  
  // Colores
  {
    seri: "tooj",
    spanish: "blanco",
    english: "white",
    category: "adjective",
    pronunciation: "/toːj/",
    examples: ["Tooj ziix", "Cosa blanca"],
    notes: "También significa 'sol' y 'día'",
  },
  {
    seri: "xnoois",
    spanish: "negro",
    english: "black",
    category: "adjective",
    pronunciation: "/xnoːis/",
    examples: ["Xnoois ziix", "Cosa negra"],
    notes: "También significa 'luna' y 'noche'",
  },
  {
    seri: "iizax",
    spanish: "azul",
    english: "blue",
    category: "adjective",
    pronunciation: "/iːzax/",
    examples: ["Iizax ziix", "Cosa azul"],
    notes: "También significa 'mar' y 'cabeza'",
  },
  {
    seri: "cöicöt",
    spanish: "rojo",
    english: "red",
    category: "adjective",
    pronunciation: "/køikøt/",
    examples: ["Cöicöt ziix", "Cosa roja"],
    notes: "También significa 'estrella'",
  },
  
  // Direcciones y ubicación
  {
    seri: "zo",
    spanish: "en",
    english: "in",
    category: "preposition",
    pronunciation: "/zo/",
    examples: ["Zo hehe", "En la casa"],
  },
  {
    seri: "hant",
    spanish: "aquí",
    english: "here",
    category: "adverb",
    pronunciation: "/hant/",
    examples: ["Hant quih iti", "Está aquí"],
    notes: "También significa 'tierra' y 'pie'",
  },
  {
    seri: "ziix",
    spanish: "allí",
    english: "there",
    category: "adverb",
    pronunciation: "/ziːx/",
    examples: ["Ziix quih iti", "Está allí"],
    notes: "Palabra polisémica - contexto determina significado",
  },
  {
    seri: "quih",
    spanish: "este / esta",
    english: "this",
    category: "pronoun",
    pronunciation: "/kih/",
    examples: ["Quih ziix", "Esta cosa"],
    notes: "También es artículo",
  },
  
  // Expresiones comunes
  {
    seri: "tahejöc",
    spanish: "gracias",
    english: "thank you",
    category: "interjection",
    pronunciation: "/tahejøk/",
    examples: ["Tahejöc", "Gracias"],
  },
  {
    seri: "tahejöc hac",
    spanish: "te agradezco",
    english: "I thank you",
    category: "interjection",
    pronunciation: "/tahejøk hak/",
    examples: ["Tahejöc hac", "Te agradezco"],
  },
  {
    seri: "ziix",
    spanish: "por favor",
    english: "please",
    category: "interjection",
    pronunciation: "/ziːx/",
    examples: ["Ziix", "Por favor"],
    notes: "Palabra polisémica - contexto determina significado",
  },
  {
    seri: "ziix hac",
    spanish: "mi favor",
    english: "my favor",
    category: "noun",
    pronunciation: "/ziːx hak/",
    examples: ["Ziix hac", "Mi favor"],
  },
  
  // Objetos comunes
  {
    seri: "hehe",
    spanish: "casa",
    english: "house",
    category: "noun",
    pronunciation: "/hehe/",
    examples: ["Hehe hac", "Mi casa"],
  },
  {
    seri: "hehe coi",
    spanish: "casas",
    english: "houses",
    category: "noun",
    pronunciation: "/hehe koːi/",
    examples: ["Hehe coi hac", "Mis casas"],
  },
  {
    seri: "hapaspoj",
    spanish: "papel",
    english: "paper",
    category: "noun",
    pronunciation: "/hapaspoj/",
    examples: ["Hapaspoj quih ano coti", "Necesito papel"],
  },
  {
    seri: "hapaspoj coi",
    spanish: "papeles",
    english: "papers",
    category: "noun",
    pronunciation: "/hapaspoj koːi/",
    examples: ["Hapaspoj coi quih ano coti", "Necesito papeles"],
  },
  {
    seri: "caacoj",
    spanish: "trabajo",
    english: "work",
    category: "noun",
    pronunciation: "/kaːkoj/",
    examples: ["Caacoj quih ano coti", "Necesito trabajo"],
  },
  {
    seri: "quííp",
    spanish: "dinero",
    english: "money",
    category: "noun",
    pronunciation: "/kiːp/",
    examples: ["Quííp quih ano coti", "Necesito dinero"],
  },
  
  // Plantas del desierto
  {
    seri: "xepe ania",
    spanish: "cactus",
    english: "cactus",
    category: "noun",
    pronunciation: "/xepe ania/",
    examples: ["Xepe ania quih iti", "El cactus está aquí"],
    notes: "También significa 'mariposa' - contexto determina significado",
  },
  {
    seri: "xepe ania coi",
    spanish: "cactos",
    english: "cacti",
    category: "noun",
    pronunciation: "/xepe ania koːi/",
    examples: ["Xepe ania coi quih iti", "Los cactos están aquí"],
  },
  
  // Conceptos abstractos adicionales
  {
    seri: "haxöl",
    spanish: "historia",
    english: "history",
    category: "noun",
    pronunciation: "/haxøl/",
    examples: ["Haxöl quih iti", "Contar una historia"],
  },
  {
    seri: "haxöl coi",
    spanish: "historias",
    english: "stories",
    category: "noun",
    pronunciation: "/haxøl koːi/",
    examples: ["Haxöl coi quih iti", "Contar historias"],
  },
  
  // Verbos de movimiento
  {
    seri: "iso",
    spanish: "ir",
    english: "to go",
    category: "verb",
    pronunciation: "/iso/",
    examples: ["Quih iso hac", "Yo voy"],
  },
  {
    seri: "quih iso",
    spanish: "ir a",
    english: "to go to",
    category: "verb",
    pronunciation: "/kih iso/",
    examples: ["Quih iso hac", "Yo voy"],
  },
  {
    seri: "iso coi",
    spanish: "ir (plural)",
    english: "to go (plural)",
    category: "verb",
    pronunciation: "/iso koːi/",
    examples: ["Iso coi hac coi", "Nosotros vamos"],
  },
  {
    seri: "isoj",
    spanish: "venir",
    english: "to come",
    category: "verb",
    pronunciation: "/isoj/",
    examples: ["Quih isoj hac", "Yo vengo"],
  },
  {
    seri: "quih isoj",
    spanish: "venir a",
    english: "to come to",
    category: "verb",
    pronunciation: "/kih isoj/",
    examples: ["Quih isoj hac", "Yo vengo"],
  },
  {
    seri: "isoj coi",
    spanish: "venir (plural)",
    english: "to come (plural)",
    category: "verb",
    pronunciation: "/isoj koːi/",
    examples: ["Isoj coi hac coi", "Nosotros venimos"],
  },
  {
    seri: "iso cöicaaj",
    spanish: "traer",
    english: "to bring",
    category: "verb",
    pronunciation: "/iso køikaːj/",
    examples: ["Quih iso cöicaaj hac", "Yo traigo"],
  },
  {
    seri: "quih iso cöicaaj",
    spanish: "traer algo",
    english: "to bring something",
    category: "verb",
    pronunciation: "/kih iso køikaːj/",
    examples: ["Quih iso cöicaaj hac", "Yo traigo algo"],
  },
  
  // Verbos de acción
  {
    seri: "ooca",
    spanish: "hacer",
    english: "to do",
    category: "verb",
    pronunciation: "/oːka/",
    examples: ["Quih ooca hac", "Yo hago"],
  },
  {
    seri: "quih ooca",
    spanish: "hacer algo",
    english: "to do something",
    category: "verb",
    pronunciation: "/kih oːka/",
    examples: ["Quih ooca hac", "Yo hago algo"],
  },
  {
    seri: "ooca coi",
    spanish: "hacer (plural)",
    english: "to do (plural)",
    category: "verb",
    pronunciation: "/oːka koːi/",
    examples: ["Ooca coi hac coi", "Nosotros hacemos"],
  },
  {
    seri: "xicaast",
    spanish: "ver",
    english: "to see",
    category: "verb",
    pronunciation: "/xikaːst/",
    examples: ["Xicaast hac", "Yo veo"],
    notes: "También significa 'enseñar'",
  },
  {
    seri: "quih xicaast",
    spanish: "ver algo",
    english: "to see something",
    category: "verb",
    pronunciation: "/kih xikaːst/",
    examples: ["Quih xicaast hac", "Yo veo algo"],
  },
  {
    seri: "xicaast coi",
    spanish: "ver (plural)",
    english: "to see (plural)",
    category: "verb",
    pronunciation: "/xikaːst koːi/",
    examples: ["Xicaast coi hac coi", "Nosotros vemos"],
  },
  {
    seri: "hapáctim quih iti",
    spanish: "escuchar",
    english: "to listen",
    category: "verb",
    pronunciation: "/hapaktim kih iti/",
    examples: ["Hapáctim quih iti hac", "Yo escucho"],
    notes: "Literalmente: 'boca estar'",
  },
  {
    seri: "quih hapáctim quih iti",
    spanish: "escuchar algo",
    english: "to listen to something",
    category: "verb",
    pronunciation: "/kih hapaktim kih iti/",
    examples: ["Quih hapáctim quih iti hac", "Yo escucho algo"],
  },
  
  // Verbos de comunicación
  {
    seri: "hapáctim quih iti",
    spanish: "decir",
    english: "to say",
    category: "verb",
    pronunciation: "/hapaktim kih iti/",
    examples: ["Hapáctim quih iti hac", "Yo digo"],
    notes: "Literalmente: 'boca estar'",
  },
  {
    seri: "quih hapáctim quih iti",
    spanish: "decir algo",
    english: "to say something",
    category: "verb",
    pronunciation: "/kih hapaktim kih iti/",
    examples: ["Quih hapáctim quih iti hac", "Yo digo algo"],
  },
  {
    seri: "hapáctim quih iti coi",
    spanish: "decir (plural)",
    english: "to say (plural)",
    category: "verb",
    pronunciation: "/hapaktim kih iti koːi/",
    examples: ["Hapáctim quih iti coi hac coi", "Nosotros decimos"],
  },
  {
    seri: "cocsar iitom quih iti",
    spanish: "hablar",
    english: "to speak",
    category: "verb",
    pronunciation: "/koksar iːtom kih iti/",
    examples: ["Cocsar iitom quih iti hac", "Yo hablo"],
  },
  {
    seri: "quih cocsar iitom quih iti",
    spanish: "hablar algo",
    english: "to speak something",
    category: "verb",
    pronunciation: "/kih koksar iːtom kih iti/",
    examples: ["Quih cocsar iitom quih iti hac", "Yo hablo algo"],
  },
  
  // Verbos de posesión
  {
    seri: "hac",
    spanish: "tener",
    english: "to have",
    category: "verb",
    pronunciation: "/hak/",
    examples: ["Hac ziix", "Tengo algo"],
    notes: "También es pronombre posesivo 'mi'",
  },
  {
    seri: "quih hac",
    spanish: "tener algo",
    english: "to have something",
    category: "verb",
    pronunciation: "/kih hak/",
    examples: ["Quih hac hac", "Yo tengo algo"],
  },
  {
    seri: "hac coi",
    spanish: "tener (plural)",
    english: "to have (plural)",
    category: "verb",
    pronunciation: "/hak koːi/",
    examples: ["Hac coi hac coi", "Nosotros tenemos"],
  },
  {
    seri: "mapt",
    spanish: "tener (tú)",
    english: "to have (you)",
    category: "verb",
    pronunciation: "/mapt/",
    examples: ["Mapt ziix", "Tú tienes algo"],
    notes: "También es pronombre posesivo 'tu'",
  },
  
  // Verbos de conocimiento
  {
    seri: "xicaast",
    spanish: "saber",
    english: "to know",
    category: "verb",
    pronunciation: "/xikaːst/",
    examples: ["Xicaast hac", "Yo sé"],
    notes: "También significa 'ver' y 'enseñar'",
  },
  {
    seri: "quih xicaast",
    spanish: "saber algo",
    english: "to know something",
    category: "verb",
    pronunciation: "/kih xikaːst/",
    examples: ["Quih xicaast hac", "Yo sé algo"],
  },
  {
    seri: "xicaast coi",
    spanish: "saber (plural)",
    english: "to know (plural)",
    category: "verb",
    pronunciation: "/xikaːst koːi/",
    examples: ["Xicaast coi hac coi", "Nosotros sabemos"],
  },
  {
    seri: "hapáctim",
    spanish: "conocer",
    english: "to know (person)",
    category: "verb",
    pronunciation: "/hapaktim/",
    examples: ["Hapáctim hac", "Yo conozco"],
    notes: "También significa 'verdad' y 'boca'",
  },
  {
    seri: "quih hapáctim",
    spanish: "conocer a alguien",
    english: "to know someone",
    category: "verb",
    pronunciation: "/kih hapaktim/",
    examples: ["Quih hapáctim hac", "Yo conozco a alguien"],
  },
  
  // Verbos de sentimiento
  {
    seri: "hapáctim quih iti",
    spanish: "querer",
    english: "to want",
    category: "verb",
    pronunciation: "/hapaktim kih iti/",
    examples: ["Hapáctim quih iti hac", "Yo quiero"],
  },
  {
    seri: "quih hapáctim quih iti",
    spanish: "querer algo",
    english: "to want something",
    category: "verb",
    pronunciation: "/kih hapaktim kih iti/",
    examples: ["Quih hapáctim quih iti hac", "Yo quiero algo"],
  },
  {
    seri: "hapáctim quih iti coi",
    spanish: "querer (plural)",
    english: "to want (plural)",
    category: "verb",
    pronunciation: "/hapaktim kih iti koːi/",
    examples: ["Hapáctim quih iti coi hac coi", "Nosotros queremos"],
  },
  {
    seri: "ziix quih iti",
    spanish: "gustar",
    english: "to like",
    category: "verb",
    pronunciation: "/ziːx kih iti/",
    examples: ["Ziix quih iti hac", "A mí me gusta"],
  },
  {
    seri: "quih ziix quih iti",
    spanish: "gustar algo",
    english: "to like something",
    category: "verb",
    pronunciation: "/kih ziːx kih iti/",
    examples: ["Quih ziix quih iti hac", "A mí me gusta algo"],
  },
  
  // Adjetivos descriptivos
  {
    seri: "tooj",
    spanish: "grande",
    english: "big",
    category: "adjective",
    pronunciation: "/toːj/",
    examples: ["Tooj ziix", "Cosa grande"],
    notes: "También significa 'sol', 'día' y 'blanco'",
  },
  {
    seri: "tooj coi",
    spanish: "grandes",
    english: "big (plural)",
    category: "adjective",
    pronunciation: "/toːj koːi/",
    examples: ["Tooj coi ziix coi", "Cosas grandes"],
  },
  {
    seri: "xnoois",
    spanish: "pequeño",
    english: "small",
    category: "adjective",
    pronunciation: "/xnoːis/",
    examples: ["Xnoois ziix", "Cosa pequeña"],
    notes: "También significa 'luna', 'noche' y 'negro'",
  },
  {
    seri: "xnoois coi",
    spanish: "pequeños",
    english: "small (plural)",
    category: "adjective",
    pronunciation: "/xnoːis koːi/",
    examples: ["Xnoois coi ziix coi", "Cosas pequeñas"],
  },
  {
    seri: "iizax",
    spanish: "bueno",
    english: "good",
    category: "adjective",
    pronunciation: "/iːzax/",
    examples: ["Iizax ziix", "Cosa buena"],
    notes: "También significa 'mar', 'cabeza' y 'azul'",
  },
  {
    seri: "iizax coi",
    spanish: "buenos",
    english: "good (plural)",
    category: "adjective",
    pronunciation: "/iːzax koːi/",
    examples: ["Iizax coi ziix coi", "Cosas buenas"],
  },
  {
    seri: "ziix",
    spanish: "malo",
    english: "bad",
    category: "adjective",
    pronunciation: "/ziːx/",
    examples: ["Ziix ziix", "Cosa mala"],
    notes: "Palabra polisémica - contexto determina significado",
  },
  {
    seri: "ziix coi",
    spanish: "malos",
    english: "bad (plural)",
    category: "adjective",
    pronunciation: "/ziːx koːi/",
    examples: ["Ziix coi ziix coi", "Cosas malas"],
  },
  
  // Partes del cuerpo adicionales
  {
    seri: "cöihcapxöt",
    spanish: "nariz",
    english: "nose",
    category: "noun",
    pronunciation: "/køihkapxøt/",
    examples: ["Cöihcapxöt hac", "Mi nariz"],
    notes: "Homónimo con 'ley' y 'ojo'",
  },
  {
    seri: "cöihcapxöt coi",
    spanish: "narices",
    english: "noses",
    category: "noun",
    pronunciation: "/køihkapxøt koːi/",
    examples: ["Cöihcapxöt coi hac", "Mis narices"],
  },
  {
    seri: "hapáctim",
    spanish: "diente",
    english: "tooth",
    category: "noun",
    pronunciation: "/hapaktim/",
    examples: ["Hapáctim hac", "Mi diente"],
    notes: "Homónimo con 'verdad', 'boca' y otros",
  },
  {
    seri: "hapáctim coi",
    spanish: "dientes",
    english: "teeth",
    category: "noun",
    pronunciation: "/hapaktim koːi/",
    examples: ["Hapáctim coi hac", "Mis dientes"],
  },
  {
    seri: "cöihyáax",
    spanish: "dedo",
    english: "finger",
    category: "noun",
    pronunciation: "/køihjaːx/",
    examples: ["Cöihyáax hac", "Mi dedo"],
    notes: "Homónimo con 'derecho' y 'mano'",
  },
  {
    seri: "cöihyáax coi",
    spanish: "dedos",
    english: "fingers",
    category: "noun",
    pronunciation: "/køihjaːx koːi/",
    examples: ["Cöihyáax coi hac", "Mis dedos"],
  },
  {
    seri: "hant",
    spanish: "dedo del pie",
    english: "toe",
    category: "noun",
    pronunciation: "/hant/",
    examples: ["Hant hac", "Mi dedo del pie"],
    notes: "Homónimo con 'tierra' y 'pie'",
  },
  {
    seri: "hant coi",
    spanish: "dedos del pie",
    english: "toes",
    category: "noun",
    pronunciation: "/hant koːi/",
    examples: ["Hant coi hac", "Mis dedos del pie"],
  },
  
  // Alimentos y comida
  {
    seri: "ziix",
    spanish: "comida",
    english: "food",
    category: "noun",
    pronunciation: "/ziːx/",
    examples: ["Ziix quih ano coti", "Necesito comida"],
    notes: "Palabra polisémica",
  },
  {
    seri: "ziix coi",
    spanish: "comidas",
    english: "foods",
    category: "noun",
    pronunciation: "/ziːx koːi/",
    examples: ["Ziix coi quih ano coti", "Necesito comidas"],
  },
  {
    seri: "iizax",
    spanish: "agua",
    english: "water",
    category: "noun",
    pronunciation: "/iːzax/",
    examples: ["Iizax quih ano coti", "Necesito agua"],
    notes: "También significa 'mar', 'cabeza', 'azul' y 'bueno'",
  },
  {
    seri: "tooj",
    spanish: "fuego",
    english: "fire",
    category: "noun",
    pronunciation: "/toːj/",
    examples: ["Tooj quih iti", "El fuego está aquí"],
    notes: "También significa 'sol', 'día', 'blanco' y 'grande'",
  },
  {
    seri: "xnoois",
    spanish: "tierra",
    english: "earth",
    category: "noun",
    pronunciation: "/xnoːis/",
    examples: ["Xnoois quih iti", "La tierra está aquí"],
    notes: "También significa 'luna', 'noche', 'negro' y 'pequeño'",
  },
  
  // Ropa y objetos personales
  {
    seri: "hehe",
    spanish: "ropa",
    english: "clothing",
    category: "noun",
    pronunciation: "/hehe/",
    examples: ["Hehe quih ano coti", "Necesito ropa"],
    notes: "También significa 'casa'",
  },
  {
    seri: "hehe coi",
    spanish: "ropas",
    english: "clothes",
    category: "noun",
    pronunciation: "/hehe koːi/",
    examples: ["Hehe coi quih ano coti", "Necesito ropas"],
  },
  {
    seri: "hapaspoj",
    spanish: "zapato",
    english: "shoe",
    category: "noun",
    pronunciation: "/hapaspoj/",
    examples: ["Hapaspoj quih ano coti", "Necesito zapato"],
    notes: "También significa 'papel'",
  },
  {
    seri: "hapaspoj coi",
    spanish: "zapatos",
    english: "shoes",
    category: "noun",
    pronunciation: "/hapaspoj koːi/",
    examples: ["Hapaspoj coi quih ano coti", "Necesito zapatos"],
  },
  
  // Lugares y geografía
  {
    seri: "hehe",
    spanish: "pueblo",
    english: "village",
    category: "noun",
    pronunciation: "/hehe/",
    examples: ["Hehe quih iti", "El pueblo está aquí"],
    notes: "También significa 'casa' y 'ropa'",
  },
  {
    seri: "hehe coi",
    spanish: "pueblos",
    english: "villages",
    category: "noun",
    pronunciation: "/hehe koːi/",
    examples: ["Hehe coi quih iti", "Los pueblos están aquí"],
  },
  {
    seri: "hant iiha",
    spanish: "montaña",
    english: "mountain",
    category: "noun",
    pronunciation: "/hant iːha/",
    examples: ["Hant iiha quih iti", "La montaña está aquí"],
    notes: "También significa 'tierra'",
  },
  {
    seri: "hant iiha coi",
    spanish: "montañas",
    english: "mountains",
    category: "noun",
    pronunciation: "/hant iːha koːi/",
    examples: ["Hant iiha coi quih iti", "Las montañas están aquí"],
  },
  {
    seri: "iizax",
    spanish: "playa",
    english: "beach",
    category: "noun",
    pronunciation: "/iːzax/",
    examples: ["Iizax quih iti", "La playa está aquí"],
    notes: "También significa 'mar', 'cabeza', 'azul' y 'bueno'",
  },
  {
    seri: "iizax coi",
    spanish: "playas",
    english: "beaches",
    category: "noun",
    pronunciation: "/iːzax koːi/",
    examples: ["Iizax coi quih iti", "Las playas están aquí"],
  },
  
  // Conceptos temporales adicionales
  {
    seri: "tooj",
    spanish: "mañana (tiempo)",
    english: "morning",
    category: "noun",
    pronunciation: "/toːj/",
    examples: ["Tooj quih iti", "La mañana está aquí"],
    notes: "También significa 'sol', 'día', 'blanco' y 'grande'",
  },
  {
    seri: "xnoois",
    spanish: "tarde",
    english: "afternoon",
    category: "noun",
    pronunciation: "/xnoːis/",
    examples: ["Xnoois quih iti", "La tarde está aquí"],
    notes: "También significa 'luna', 'noche', 'negro' y 'pequeño'",
  },
  {
    seri: "tooj xnoois",
    spanish: "semana",
    english: "week",
    category: "noun",
    pronunciation: "/toːj xnoːis/",
    examples: ["Tooj xnoois quih iti", "La semana está aquí"],
    notes: "También significa 'hoy'",
  },
  {
    seri: "tooj xnoois coi",
    spanish: "semanas",
    english: "weeks",
    category: "noun",
    pronunciation: "/toːj xnoːis koːi/",
    examples: ["Tooj xnoois coi quih iti", "Las semanas están aquí"],
  },
  
  // Expresiones de cortesía
  {
    seri: "hant",
    spanish: "hola",
    english: "hello",
    category: "interjection",
    pronunciation: "/hant/",
    examples: ["Hant", "Hola", "Hant hac", "Hola (yo saludo)"],
    notes: "Saludo común. PRIORIDAD: Cuando 'Hant' aparece solo o como saludo, traducir como 'hola'. También puede significar 'aquí', 'tierra', 'pie', 'dónde', 'inicio' según contexto, pero 'hola' es el significado primario para saludos.",
    culturalContext: "Saludo más común en comca'ac. Se usa al encontrarse con alguien.",
  },
  {
    seri: "tahejöc",
    spanish: "de nada",
    english: "you're welcome",
    category: "interjection",
    pronunciation: "/tahejøk/",
    examples: ["Tahejöc", "De nada"],
    notes: "También significa 'gracias'",
  },
  {
    seri: "ziix",
    spanish: "disculpa",
    english: "excuse me",
    category: "interjection",
    pronunciation: "/ziːx/",
    examples: ["Ziix", "Disculpa"],
    notes: "Palabra polisémica",
  },
  {
    seri: "ziix hac",
    spanish: "lo siento",
    english: "I'm sorry",
    category: "interjection",
    pronunciation: "/ziːx hak/",
    examples: ["Ziix hac", "Lo siento"],
  },
  
  // Preguntas comunes
  {
    seri: "quih",
    spanish: "qué",
    english: "what",
    category: "pronoun",
    pronunciation: "/kih/",
    examples: ["Quih ano coti?", "¿Qué necesitas?"],
    notes: "También es artículo y demostrativo",
  },
  {
    seri: "haxt",
    spanish: "quién",
    english: "who",
    category: "pronoun",
    pronunciation: "/haxt/",
    examples: ["Haxt quih iti?", "¿Quién está aquí?"],
    notes: "También significa 'persona'",
  },
  {
    seri: "hant",
    spanish: "dónde",
    english: "where",
    category: "pronoun",
    pronunciation: "/hant/",
    examples: ["Hant quih iti?", "¿Dónde está?"],
    notes: "También significa 'tierra', 'pie' y 'aquí'",
  },
  {
    seri: "quih ano coti",
    spanish: "por qué",
    english: "why",
    category: "pronoun",
    pronunciation: "/kih ano koti/",
    examples: ["Quih ano coti quih iti?", "¿Por qué está aquí?"],
  },
  
  // Conjunciones y conectores
  {
    seri: "quih",
    spanish: "y",
    english: "and",
    category: "conjunction",
    pronunciation: "/kih/",
    examples: ["Quih ziix quih ziix", "Cosa y cosa"],
    notes: "También es artículo, demostrativo y pronombre",
  },
  {
    seri: "ziix",
    spanish: "o",
    english: "or",
    category: "conjunction",
    pronunciation: "/ziːx/",
    examples: ["Ziix quih ziix", "Cosa o cosa"],
    notes: "Palabra polisémica",
  },
  {
    seri: "ziix quih",
    spanish: "pero",
    english: "but",
    category: "conjunction",
    pronunciation: "/ziːx kih/",
    examples: ["Ziix quih ziix", "Cosa pero cosa"],
  },
  
  // Adverbios de modo
  {
    seri: "tooj",
    spanish: "bien",
    english: "well",
    category: "adverb",
    pronunciation: "/toːj/",
    examples: ["Tooj quih iti", "Está bien"],
    notes: "También significa 'sol', 'día', 'blanco' y 'grande'",
  },
  {
    seri: "ziix",
    spanish: "mal",
    english: "badly",
    category: "adverb",
    pronunciation: "/ziːx/",
    examples: ["Ziix quih iti", "Está mal"],
    notes: "Palabra polisémica",
  },
  {
    seri: "iizax",
    spanish: "mucho",
    english: "much",
    category: "adverb",
    pronunciation: "/iːzax/",
    examples: ["Iizax quih iti", "Hay mucho"],
    notes: "También significa 'mar', 'cabeza', 'azul' y 'bueno'",
  },
  {
    seri: "xnoois",
    spanish: "poco",
    english: "little",
    category: "adverb",
    pronunciation: "/xnoːis/",
    examples: ["Xnoois quih iti", "Hay poco"],
    notes: "También significa 'luna', 'noche', 'negro' y 'pequeño'",
  },
  
  // Verbos adicionales - Acciones físicas
  {
    seri: "iso",
    spanish: "caminar",
    english: "to walk",
    category: "verb",
    pronunciation: "/iso/",
    examples: ["Quih iso hac", "Yo camino"],
  },
  {
    seri: "quih iso",
    spanish: "caminar hacia",
    english: "to walk to",
    category: "verb",
    pronunciation: "/kih iso/",
    examples: ["Quih iso hac", "Yo camino hacia"],
  },
  {
    seri: "isoj",
    spanish: "correr",
    english: "to run",
    category: "verb",
    pronunciation: "/isoj/",
    examples: ["Quih isoj hac", "Yo corro"],
  },
  {
    seri: "quih isoj",
    spanish: "correr hacia",
    english: "to run to",
    category: "verb",
    pronunciation: "/kih isoj/",
    examples: ["Quih isoj hac", "Yo corro hacia"],
  },
  {
    seri: "iso cöicaaj",
    spanish: "saltar",
    english: "to jump",
    category: "verb",
    pronunciation: "/iso køikaːj/",
    examples: ["Quih iso cöicaaj hac", "Yo salto"],
  },
  {
    seri: "quih iso cöicaaj",
    spanish: "saltar sobre",
    english: "to jump over",
    category: "verb",
    pronunciation: "/kih iso køikaːj/",
    examples: ["Quih iso cöicaaj hac", "Yo salto sobre"],
  },
  {
    seri: "ooca",
    spanish: "sentar",
    english: "to sit",
    category: "verb",
    pronunciation: "/oːka/",
    examples: ["Quih ooca hac", "Yo me siento"],
    notes: "También significa 'hacer' y 'ayudar'",
  },
  {
    seri: "quih ooca",
    spanish: "sentarse",
    english: "to sit down",
    category: "verb",
    pronunciation: "/kih oːka/",
    examples: ["Quih ooca hac", "Yo me siento"],
  },
  {
    seri: "xicaast",
    spanish: "parar",
    english: "to stand",
    category: "verb",
    pronunciation: "/xikaːst/",
    examples: ["Xicaast hac", "Yo me paro"],
    notes: "También significa 'ver', 'saber' y 'enseñar'",
  },
  {
    seri: "quih xicaast",
    spanish: "pararse",
    english: "to stand up",
    category: "verb",
    pronunciation: "/kih xikaːst/",
    examples: ["Quih xicaast hac", "Yo me paro"],
  },
  {
    seri: "hapáctim quih iti",
    spanish: "dormir",
    english: "to sleep",
    category: "verb",
    pronunciation: "/hapaktim kih iti/",
    examples: ["Hapáctim quih iti hac", "Yo duermo"],
  },
  {
    seri: "quih hapáctim quih iti",
    spanish: "dormirse",
    english: "to fall asleep",
    category: "verb",
    pronunciation: "/kih hapaktim kih iti/",
    examples: ["Quih hapáctim quih iti hac", "Yo me duermo"],
  },
  {
    seri: "iso",
    spanish: "comer",
    english: "to eat",
    category: "verb",
    pronunciation: "/iso/",
    examples: ["Quih iso hac", "Yo como"],
    notes: "También significa 'ir' y 'caminar'",
  },
  {
    seri: "quih iso",
    spanish: "comer algo",
    english: "to eat something",
    category: "verb",
    pronunciation: "/kih iso/",
    examples: ["Quih iso hac", "Yo como algo"],
  },
  {
    seri: "iizax",
    spanish: "beber",
    english: "to drink",
    category: "verb",
    pronunciation: "/iːzax/",
    examples: ["Quih iizax hac", "Yo bebo"],
    notes: "También significa 'mar', 'cabeza', 'azul' y 'bueno'",
  },
  {
    seri: "quih iizax",
    spanish: "beber algo",
    english: "to drink something",
    category: "verb",
    pronunciation: "/kih iːzax/",
    examples: ["Quih iizax hac", "Yo bebo algo"],
  },
  
  // Verbos de manipulación
  {
    seri: "cöihyáax",
    spanish: "tomar",
    english: "to take",
    category: "verb",
    pronunciation: "/køihjaːx/",
    examples: ["Quih cöihyáax hac", "Yo tomo"],
    notes: "También significa 'derecho' y 'mano'",
  },
  {
    seri: "quih cöihyáax",
    spanish: "tomar algo",
    english: "to take something",
    category: "verb",
    pronunciation: "/kih køihjaːx/",
    examples: ["Quih cöihyáax hac", "Yo tomo algo"],
  },
  {
    seri: "cöihyáax coi",
    spanish: "dar",
    english: "to give",
    category: "verb",
    pronunciation: "/køihjaːx koːi/",
    examples: ["Cöihyáax coi hac", "Yo doy"],
  },
  {
    seri: "quih cöihyáax coi",
    spanish: "dar algo",
    english: "to give something",
    category: "verb",
    pronunciation: "/kih køihjaːx koːi/",
    examples: ["Quih cöihyáax coi hac", "Yo doy algo"],
  },
  {
    seri: "hant",
    spanish: "poner",
    english: "to put",
    category: "verb",
    pronunciation: "/hant/",
    examples: ["Quih hant hac", "Yo pongo"],
    notes: "También significa 'tierra', 'pie' y 'aquí'",
  },
  {
    seri: "quih hant",
    spanish: "poner algo",
    english: "to put something",
    category: "verb",
    pronunciation: "/kih hant/",
    examples: ["Quih hant hac", "Yo pongo algo"],
  },
  {
    seri: "ziix",
    spanish: "quitar",
    english: "to remove",
    category: "verb",
    pronunciation: "/ziːx/",
    examples: ["Quih ziix hac", "Yo quito"],
    notes: "Palabra polisémica",
  },
  {
    seri: "quih ziix",
    spanish: "quitar algo",
    english: "to remove something",
    category: "verb",
    pronunciation: "/kih ziːx/",
    examples: ["Quih ziix hac", "Yo quito algo"],
  },
  
  // Verbos de percepción
  {
    seri: "cöihcapxöt",
    spanish: "mirar",
    english: "to look",
    category: "verb",
    pronunciation: "/køihkapxøt/",
    examples: ["Quih cöihcapxöt hac", "Yo miro"],
    notes: "También significa 'ley' y 'ojo'",
  },
  {
    seri: "quih cöihcapxöt",
    spanish: "mirar algo",
    english: "to look at something",
    category: "verb",
    pronunciation: "/kih køihkapxøt/",
    examples: ["Quih cöihcapxöt hac", "Yo miro algo"],
  },
  {
    seri: "hapáctim",
    spanish: "oler",
    english: "to smell",
    category: "verb",
    pronunciation: "/hapaktim/",
    examples: ["Quih hapáctim hac", "Yo huelo"],
    notes: "También significa 'verdad', 'boca' y otros",
  },
  {
    seri: "quih hapáctim",
    spanish: "oler algo",
    english: "to smell something",
    category: "verb",
    pronunciation: "/kih hapaktim/",
    examples: ["Quih hapáctim hac", "Yo huelo algo"],
  },
  {
    seri: "cöihyáax",
    spanish: "tocar",
    english: "to touch",
    category: "verb",
    pronunciation: "/køihjaːx/",
    examples: ["Quih cöihyáax hac", "Yo toco"],
    notes: "También significa 'derecho' y 'mano'",
  },
  {
    seri: "quih cöihyáax",
    spanish: "tocar algo",
    english: "to touch something",
    category: "verb",
    pronunciation: "/kih køihjaːx/",
    examples: ["Quih cöihyáax hac", "Yo toco algo"],
  },
  
  // Verbos de creación y construcción
  {
    seri: "ooca",
    spanish: "crear",
    english: "to create",
    category: "verb",
    pronunciation: "/oːka/",
    examples: ["Quih ooca hac", "Yo creo"],
    notes: "También significa 'hacer' y 'ayudar'",
  },
  {
    seri: "quih ooca",
    spanish: "crear algo",
    english: "to create something",
    category: "verb",
    pronunciation: "/kih oːka/",
    examples: ["Quih ooca hac", "Yo creo algo"],
  },
  {
    seri: "hehe",
    spanish: "construir",
    english: "to build",
    category: "verb",
    pronunciation: "/hehe/",
    examples: ["Quih hehe hac", "Yo construyo"],
    notes: "También significa 'casa', 'ropa' y 'pueblo'",
  },
  {
    seri: "quih hehe",
    spanish: "construir algo",
    english: "to build something",
    category: "verb",
    pronunciation: "/kih hehe/",
    examples: ["Quih hehe hac", "Yo construyo algo"],
  },
  {
    seri: "ziix",
    spanish: "hacer",
    english: "to make",
    category: "verb",
    pronunciation: "/ziːx/",
    examples: ["Quih ziix hac", "Yo hago"],
    notes: "Palabra polisémica",
  },
  {
    seri: "quih ziix",
    spanish: "hacer algo",
    english: "to make something",
    category: "verb",
    pronunciation: "/kih ziːx/",
    examples: ["Quih ziix hac", "Yo hago algo"],
  },
  
  // Verbos de destrucción
  {
    seri: "ziix coii",
    spanish: "romper",
    english: "to break",
    category: "verb",
    pronunciation: "/ziːx koːi/",
    examples: ["Quih ziix coii hac", "Yo rompo"],
    notes: "También significa 'violación'",
  },
  {
    seri: "quih ziix coii",
    spanish: "romper algo",
    english: "to break something",
    category: "verb",
    pronunciation: "/kih ziːx koːi/",
    examples: ["Quih ziix coii hac", "Yo rompo algo"],
  },
  {
    seri: "tooj",
    spanish: "quemar",
    english: "to burn",
    category: "verb",
    pronunciation: "/toːj/",
    examples: ["Quih tooj hac", "Yo quemo"],
    notes: "También significa 'sol', 'día', 'blanco' y 'grande'",
  },
  {
    seri: "quih tooj",
    spanish: "quemar algo",
    english: "to burn something",
    category: "verb",
    pronunciation: "/kih toːj/",
    examples: ["Quih tooj hac", "Yo quemo algo"],
  },
  
  // Verbos de movimiento de objetos
  {
    seri: "iso cöicaaj",
    spanish: "lanzar",
    english: "to throw",
    category: "verb",
    pronunciation: "/iso køikaːj/",
    examples: ["Quih iso cöicaaj hac", "Yo lanzo"],
    notes: "También significa 'traer' y 'saltar'",
  },
  {
    seri: "quih iso cöicaaj",
    spanish: "lanzar algo",
    english: "to throw something",
    category: "verb",
    pronunciation: "/kih iso køikaːj/",
    examples: ["Quih iso cöicaaj hac", "Yo lanzo algo"],
  },
  {
    seri: "isoj",
    spanish: "empujar",
    english: "to push",
    category: "verb",
    pronunciation: "/isoj/",
    examples: ["Quih isoj hac", "Yo empujo"],
    notes: "También significa 'venir' y 'correr'",
  },
  {
    seri: "quih isoj",
    spanish: "empujar algo",
    english: "to push something",
    category: "verb",
    pronunciation: "/kih isoj/",
    examples: ["Quih isoj hac", "Yo empujo algo"],
  },
  {
    seri: "iso",
    spanish: "jalar",
    english: "to pull",
    category: "verb",
    pronunciation: "/iso/",
    examples: ["Quih iso hac", "Yo jalo"],
    notes: "También significa 'ir', 'caminar' y 'comer'",
  },
  {
    seri: "quih iso",
    spanish: "jalar algo",
    english: "to pull something",
    category: "verb",
    pronunciation: "/kih iso/",
    examples: ["Quih iso hac", "Yo jalo algo"],
  },
  
  // Verbos de emoción y estado mental
  {
    seri: "hapáctim quih iti",
    spanish: "reír",
    english: "to laugh",
    category: "verb",
    pronunciation: "/hapaktim kih iti/",
    examples: ["Hapáctim quih iti hac", "Yo río"],
  },
  {
    seri: "quih hapáctim quih iti",
    spanish: "reírse",
    english: "to laugh",
    category: "verb",
    pronunciation: "/kih hapaktim kih iti/",
    examples: ["Quih hapáctim quih iti hac", "Yo me río"],
  },
  {
    seri: "ziix quih iti",
    spanish: "llorar",
    english: "to cry",
    category: "verb",
    pronunciation: "/ziːx kih iti/",
    examples: ["Ziix quih iti hac", "Yo lloro"],
  },
  {
    seri: "quih ziix quih iti",
    spanish: "llorar por",
    english: "to cry for",
    category: "verb",
    pronunciation: "/kih ziːx kih iti/",
    examples: ["Quih ziix quih iti hac", "Yo lloro por"],
  },
  {
    seri: "cöihcapxöt quih iti",
    spanish: "sorprender",
    english: "to surprise",
    category: "verb",
    pronunciation: "/køihkapxøt kih iti/",
    examples: ["Cöihcapxöt quih iti hac", "Yo sorprendo"],
    notes: "También significa 'ley' y 'ojo'",
  },
  {
    seri: "quih cöihcapxöt quih iti",
    spanish: "sorprender a alguien",
    english: "to surprise someone",
    category: "verb",
    pronunciation: "/kih køihkapxøt kih iti/",
    examples: ["Quih cöihcapxöt quih iti hac", "Yo sorprendo a alguien"],
  },
  
  // Verbos de aprendizaje y enseñanza
  {
    seri: "xicaast",
    spanish: "aprender",
    english: "to learn",
    category: "verb",
    pronunciation: "/xikaːst/",
    examples: ["Xicaast hac", "Yo aprendo"],
    notes: "También significa 'ver', 'saber' y 'enseñar'",
  },
  {
    seri: "quih xicaast",
    spanish: "aprender algo",
    english: "to learn something",
    category: "verb",
    pronunciation: "/kih xikaːst/",
    examples: ["Quih xicaast hac", "Yo aprendo algo"],
  },
  {
    seri: "xicaast coi",
    spanish: "enseñar",
    english: "to teach",
    category: "verb",
    pronunciation: "/xikaːst koːi/",
    examples: ["Xicaast coi hac", "Yo enseño"],
  },
  {
    seri: "quih xicaast coi",
    spanish: "enseñar algo",
    english: "to teach something",
    category: "verb",
    pronunciation: "/kih xikaːst koːi/",
    examples: ["Quih xicaast coi hac", "Yo enseño algo"],
  },
  {
    seri: "hapáctim quih iti",
    spanish: "estudiar",
    english: "to study",
    category: "verb",
    pronunciation: "/hapaktim kih iti/",
    examples: ["Hapáctim quih iti hac", "Yo estudio"],
  },
  {
    seri: "quih hapáctim quih iti",
    spanish: "estudiar algo",
    english: "to study something",
    category: "verb",
    pronunciation: "/kih hapaktim kih iti/",
    examples: ["Quih hapáctim quih iti hac", "Yo estudio algo"],
  },
  
  // Verbos de trabajo y actividad
  {
    seri: "caacoj",
    spanish: "trabajar",
    english: "to work",
    category: "verb",
    pronunciation: "/kaːkoj/",
    examples: ["Quih caacoj hac", "Yo trabajo"],
    notes: "También significa 'trabajo' (sustantivo)",
  },
  {
    seri: "quih caacoj",
    spanish: "trabajar en",
    english: "to work on",
    category: "verb",
    pronunciation: "/kih kaːkoj/",
    examples: ["Quih caacoj hac", "Yo trabajo en"],
  },
  {
    seri: "ooca",
    spanish: "ayudar",
    english: "to help",
    category: "verb",
    pronunciation: "/oːka/",
    examples: ["Quih ooca hac", "Yo ayudo"],
    notes: "También significa 'hacer' y 'crear'",
  },
  {
    seri: "quih ooca",
    spanish: "ayudar a alguien",
    english: "to help someone",
    category: "verb",
    pronunciation: "/kih oːka/",
    examples: ["Quih ooca hac", "Yo ayudo a alguien"],
  },
  {
    seri: "ziix",
    spanish: "buscar",
    english: "to search",
    category: "verb",
    pronunciation: "/ziːx/",
    examples: ["Quih ziix hac", "Yo busco"],
    notes: "Palabra polisémica",
  },
  {
    seri: "quih ziix",
    spanish: "buscar algo",
    english: "to search for something",
    category: "verb",
    pronunciation: "/kih ziːx/",
    examples: ["Quih ziix hac", "Yo busco algo"],
  },
  {
    seri: "xicaast",
    spanish: "encontrar",
    english: "to find",
    category: "verb",
    pronunciation: "/xikaːst/",
    examples: ["Xicaast hac", "Yo encuentro"],
    notes: "También significa 'ver', 'saber' y 'enseñar'",
  },
  {
    seri: "quih xicaast",
    spanish: "encontrar algo",
    english: "to find something",
    category: "verb",
    pronunciation: "/kih xikaːst/",
    examples: ["Quih xicaast hac", "Yo encuentro algo"],
  },
  
  // Verbos de compra y venta
  {
    seri: "quííp",
    spanish: "comprar",
    english: "to buy",
    category: "verb",
    pronunciation: "/kiːp/",
    examples: ["Quih quííp hac", "Yo compro"],
    notes: "También significa 'dinero'",
  },
  {
    seri: "quih quííp",
    spanish: "comprar algo",
    english: "to buy something",
    category: "verb",
    pronunciation: "/kih kiːp/",
    examples: ["Quih quííp hac", "Yo compro algo"],
  },
  {
    seri: "quííp coi",
    spanish: "vender",
    english: "to sell",
    category: "verb",
    pronunciation: "/kiːp koːi/",
    examples: ["Quííp coi hac", "Yo vendo"],
  },
  {
    seri: "quih quííp coi",
    spanish: "vender algo",
    english: "to sell something",
    category: "verb",
    pronunciation: "/kih kiːp koːi/",
    examples: ["Quih quííp coi hac", "Yo vendo algo"],
  },
  
  // Verbos de limpieza
  {
    seri: "iizax",
    spanish: "limpiar",
    english: "to clean",
    category: "verb",
    pronunciation: "/iːzax/",
    examples: ["Quih iizax hac", "Yo limpio"],
    notes: "También significa 'mar', 'cabeza', 'azul' y 'bueno'",
  },
  {
    seri: "quih iizax",
    spanish: "limpiar algo",
    english: "to clean something",
    category: "verb",
    pronunciation: "/kih iːzax/",
    examples: ["Quih iizax hac", "Yo limpio algo"],
  },
  {
    seri: "tooj",
    spanish: "lavar",
    english: "to wash",
    category: "verb",
    pronunciation: "/toːj/",
    examples: ["Quih tooj hac", "Yo lavo"],
    notes: "También significa 'sol', 'día', 'blanco' y 'grande'",
  },
  {
    seri: "quih tooj",
    spanish: "lavar algo",
    english: "to wash something",
    category: "verb",
    pronunciation: "/kih toːj/",
    examples: ["Quih tooj hac", "Yo lavo algo"],
  },
  
  // Más animales terrestres
  {
    seri: "xepe ania",
    spanish: "pájaro",
    english: "bird",
    category: "noun",
    pronunciation: "/xepe ania/",
    examples: ["Xepe ania quih iti", "El pájaro está aquí"],
    notes: "También significa 'mariposa' y 'cactus'",
  },
  {
    seri: "xepe ania coi",
    spanish: "pájaros",
    english: "birds",
    category: "noun",
    pronunciation: "/xepe ania koːi/",
    examples: ["Xepe ania coi quih iti", "Los pájaros están aquí"],
  },
  {
    seri: "cocáac",
    spanish: "águila",
    english: "eagle",
    category: "noun",
    pronunciation: "/kokaːk/",
    examples: ["Cocáac quih iti", "El águila está aquí"],
    notes: "También significa 'pelícano'",
  },
  {
    seri: "cocáac coi",
    spanish: "águilas",
    english: "eagles",
    category: "noun",
    pronunciation: "/kokaːk koːi/",
    examples: ["Cocáac coi quih iti", "Las águilas están aquí"],
  },
  {
    seri: "cöicaaj",
    spanish: "coyote",
    english: "coyote",
    category: "noun",
    pronunciation: "/køikaːj/",
    examples: ["Cöicaaj quih iti", "El coyote está aquí"],
    notes: "También significa 'tortuga marina'",
  },
  {
    seri: "cöicaaj coi",
    spanish: "coyotes",
    english: "coyotes",
    category: "noun",
    pronunciation: "/køikaːj koːi/",
    examples: ["Cöicaaj coi quih iti", "Los coyotes están aquí"],
  },
  {
    seri: "ziix",
    spanish: "serpiente",
    english: "snake",
    category: "noun",
    pronunciation: "/ziːx/",
    examples: ["Ziix quih iti", "La serpiente está aquí"],
    notes: "Palabra polisémica",
  },
  {
    seri: "ziix coi",
    spanish: "serpientes",
    english: "snakes",
    category: "noun",
    pronunciation: "/ziːx koːi/",
    examples: ["Ziix coi quih iti", "Las serpientes están aquí"],
  },
  
  // Plantas y vegetación
  {
    seri: "xepe ania",
    spanish: "árbol",
    english: "tree",
    category: "noun",
    pronunciation: "/xepe ania/",
    examples: ["Xepe ania quih iti", "El árbol está aquí"],
    notes: "También significa 'mariposa', 'cactus' y 'pájaro'",
  },
  {
    seri: "xepe ania coi",
    spanish: "árboles",
    english: "trees",
    category: "noun",
    pronunciation: "/xepe ania koːi/",
    examples: ["Xepe ania coi quih iti", "Los árboles están aquí"],
  },
  {
    seri: "hant",
    spanish: "planta",
    english: "plant",
    category: "noun",
    pronunciation: "/hant/",
    examples: ["Hant quih iti", "La planta está aquí"],
    notes: "También significa 'tierra', 'pie' y 'aquí'",
  },
  {
    seri: "hant coi",
    spanish: "plantas",
    english: "plants",
    category: "noun",
    pronunciation: "/hant koːi/",
    examples: ["Hant coi quih iti", "Las plantas están aquí"],
  },
  {
    seri: "tooj",
    spanish: "flor",
    english: "flower",
    category: "noun",
    pronunciation: "/toːj/",
    examples: ["Tooj quih iti", "La flor está aquí"],
    notes: "También significa 'sol', 'día', 'blanco' y 'grande'",
  },
  {
    seri: "tooj coi",
    spanish: "flores",
    english: "flowers",
    category: "noun",
    pronunciation: "/toːj koːi/",
    examples: ["Tooj coi quih iti", "Las flores están aquí"],
  },
  
  // Objetos del hogar
  {
    seri: "hehe",
    spanish: "mesa",
    english: "table",
    category: "noun",
    pronunciation: "/hehe/",
    examples: ["Hehe quih iti", "La mesa está aquí"],
    notes: "También significa 'casa', 'ropa' y 'pueblo'",
  },
  {
    seri: "hehe coi",
    spanish: "mesas",
    english: "tables",
    category: "noun",
    pronunciation: "/hehe koːi/",
    examples: ["Hehe coi quih iti", "Las mesas están aquí"],
  },
  {
    seri: "ooca",
    spanish: "silla",
    english: "chair",
    category: "noun",
    pronunciation: "/oːka/",
    examples: ["Ooca quih iti", "La silla está aquí"],
    notes: "También significa 'hacer', 'ayudar' y 'crear'",
  },
  {
    seri: "ooca coi",
    spanish: "sillas",
    english: "chairs",
    category: "noun",
    pronunciation: "/oːka koːi/",
    examples: ["Ooca coi quih iti", "Las sillas están aquí"],
  },
  {
    seri: "hapaspoj",
    spanish: "libro",
    english: "book",
    category: "noun",
    pronunciation: "/hapaspoj/",
    examples: ["Hapaspoj quih iti", "El libro está aquí"],
    notes: "También significa 'papel' y 'zapato'",
  },
  {
    seri: "hapaspoj coi",
    spanish: "libros",
    english: "books",
    category: "noun",
    pronunciation: "/hapaspoj koːi/",
    examples: ["Hapaspoj coi quih iti", "Los libros están aquí"],
  },
  
  // Partes del cuerpo adicionales
  {
    seri: "cöihcapxöt",
    spanish: "cara",
    english: "face",
    category: "noun",
    pronunciation: "/køihkapxøt/",
    examples: ["Cöihcapxöt hac", "Mi cara"],
    notes: "También significa 'ley' y 'ojo'",
  },
  {
    seri: "iizax",
    spanish: "cabello",
    english: "hair",
    category: "noun",
    pronunciation: "/iːzax/",
    examples: ["Iizax hac", "Mi cabello"],
    notes: "También significa 'mar', 'cabeza', 'azul' y 'bueno'",
  },
  {
    seri: "cöihyáax",
    spanish: "brazo",
    english: "arm",
    category: "noun",
    pronunciation: "/køihjaːx/",
    examples: ["Cöihyáax hac", "Mi brazo"],
    notes: "También significa 'derecho' y 'mano'",
  },
  {
    seri: "cöihyáax coi",
    spanish: "brazos",
    english: "arms",
    category: "noun",
    pronunciation: "/køihjaːx koːi/",
    examples: ["Cöihyáax coi hac", "Mis brazos"],
  },
  {
    seri: "hant",
    spanish: "pierna",
    english: "leg",
    category: "noun",
    pronunciation: "/hant/",
    examples: ["Hant hac", "Mi pierna"],
    notes: "También significa 'tierra', 'pie' y 'aquí'",
  },
  {
    seri: "hant coi",
    spanish: "piernas",
    english: "legs",
    category: "noun",
    pronunciation: "/hant koːi/",
    examples: ["Hant coi hac", "Mis piernas"],
  },
  {
    seri: "cöihcaaitoj",
    spanish: "pecho",
    english: "chest",
    category: "noun",
    pronunciation: "/køihkaːitoj/",
    examples: ["Cöihcaaitoj hac", "Mi pecho"],
    notes: "También significa 'testigo' y 'corazón'",
  },
  {
    seri: "iizax",
    spanish: "espalda",
    english: "back",
    category: "noun",
    pronunciation: "/iːzax/",
    examples: ["Iizax hac", "Mi espalda"],
    notes: "También significa 'mar', 'cabeza', 'azul' y 'bueno'",
  },
  
  // Adjetivos adicionales
  {
    seri: "tooj",
    spanish: "alto",
    english: "tall",
    category: "adjective",
    pronunciation: "/toːj/",
    examples: ["Tooj haxt", "Persona alta"],
    notes: "También significa 'sol', 'día', 'blanco' y 'grande'",
  },
  {
    seri: "xnoois",
    spanish: "bajo",
    english: "short",
    category: "adjective",
    pronunciation: "/xnoːis/",
    examples: ["Xnoois haxt", "Persona baja"],
    notes: "También significa 'luna', 'noche', 'negro' y 'pequeño'",
  },
  {
    seri: "iizax",
    spanish: "nuevo",
    english: "new",
    category: "adjective",
    pronunciation: "/iːzax/",
    examples: ["Iizax ziix", "Cosa nueva"],
    notes: "También significa 'mar', 'cabeza', 'azul' y 'bueno'",
  },
  {
    seri: "ziix",
    spanish: "viejo",
    english: "old",
    category: "adjective",
    pronunciation: "/ziːx/",
    examples: ["Ziix haxt", "Persona vieja"],
    notes: "Palabra polisémica",
  },
  {
    seri: "tooj",
    spanish: "joven",
    english: "young",
    category: "adjective",
    pronunciation: "/toːj/",
    examples: ["Tooj haxt", "Persona joven"],
    notes: "También significa 'sol', 'día', 'blanco' y 'grande'",
  },
  {
    seri: "cöicöt",
    spanish: "caliente",
    english: "hot",
    category: "adjective",
    pronunciation: "/køikøt/",
    examples: ["Cöicöt ziix", "Cosa caliente"],
    notes: "También significa 'estrella' y 'rojo'",
  },
  {
    seri: "xnoois",
    spanish: "frío",
    english: "cold",
    category: "adjective",
    pronunciation: "/xnoːis/",
    examples: ["Xnoois ziix", "Cosa fría"],
    notes: "También significa 'luna', 'noche', 'negro' y 'pequeño'",
  },
  {
    seri: "iizax",
    spanish: "rápido",
    english: "fast",
    category: "adjective",
    pronunciation: "/iːzax/",
    examples: ["Iizax haxt", "Persona rápida"],
    notes: "También significa 'mar', 'cabeza', 'azul' y 'bueno'",
  },
  {
    seri: "xnoois",
    spanish: "lento",
    english: "slow",
    category: "adjective",
    pronunciation: "/xnoːis/",
    examples: ["Xnoois haxt", "Persona lenta"],
    notes: "También significa 'luna', 'noche', 'negro' y 'pequeño'",
  },
  
  // Números adicionales (11-20)
  {
    seri: "coi coi coj tazo",
    spanish: "once",
    english: "eleven",
    category: "noun",
    pronunciation: "/koːi koːi koj tazo/",
    examples: ["Coi coi coj tazo ziix coi", "Once cosas"],
  },
  {
    seri: "coi coi coj coj",
    spanish: "doce",
    english: "twelve",
    category: "noun",
    pronunciation: "/koːi koːi koj koj/",
    examples: ["Coi coi coj coj ziix coi", "Doce cosas"],
  },
  {
    seri: "coi coi coj capxöt",
    spanish: "trece",
    english: "thirteen",
    category: "noun",
    pronunciation: "/koːi koːi koj kapxøt/",
    examples: ["Coi coi coj capxöt ziix coi", "Trece cosas"],
  },
  {
    seri: "coi coi coi",
    spanish: "catorce",
    english: "fourteen",
    category: "noun",
    pronunciation: "/koːi koːi koːi/",
    examples: ["Coi coi coi ziix coi", "Catorce cosas"],
  },
  {
    seri: "coi coi coi tazo",
    spanish: "quince",
    english: "fifteen",
    category: "noun",
    pronunciation: "/koːi koːi koːi tazo/",
    examples: ["Coi coi coi tazo ziix coi", "Quince cosas"],
  },
  {
    seri: "coi coi coi coj",
    spanish: "dieciséis",
    english: "sixteen",
    category: "noun",
    pronunciation: "/koːi koːi koːi koj/",
    examples: ["Coi coi coi coj ziix coi", "Dieciséis cosas"],
  },
  {
    seri: "coi coi coi capxöt",
    spanish: "diecisiete",
    english: "seventeen",
    category: "noun",
    pronunciation: "/koːi koːi koːi kapxøt/",
    examples: ["Coi coi coi capxöt ziix coi", "Diecisiete cosas"],
  },
  {
    seri: "coi coi coi coi",
    spanish: "dieciocho",
    english: "eighteen",
    category: "noun",
    pronunciation: "/koːi koːi koːi koːi/",
    examples: ["Coi coi coi coi ziix coi", "Dieciocho cosas"],
  },
  {
    seri: "coi coi coi coi tazo",
    spanish: "diecinueve",
    english: "nineteen",
    category: "noun",
    pronunciation: "/koːi koːi koːi koːi tazo/",
    examples: ["Coi coi coi coi tazo ziix coi", "Diecinueve cosas"],
  },
  {
    seri: "coi coi coi coi coj",
    spanish: "veinte",
    english: "twenty",
    category: "noun",
    pronunciation: "/koːi koːi koːi koːi koj/",
    examples: ["Coi coi coi coi coj ziix coi", "Veinte cosas"],
  },
  
  // Conceptos abstractos adicionales
  {
    seri: "hapáctim",
    spanish: "amor",
    english: "love",
    category: "noun",
    pronunciation: "/hapaktim/",
    examples: ["Hapáctim quih iti", "El amor está aquí"],
    notes: "También significa 'verdad', 'boca' y otros",
  },
  {
    seri: "ziix",
    spanish: "odio",
    english: "hate",
    category: "noun",
    pronunciation: "/ziːx/",
    examples: ["Ziix quih iti", "El odio está aquí"],
    notes: "Palabra polisémica",
  },
  {
    seri: "cöihcapxöt",
    spanish: "paz",
    english: "peace",
    category: "noun",
    pronunciation: "/køihkapxøt/",
    examples: ["Cöihcapxöt quih iti", "La paz está aquí"],
    notes: "También significa 'ley' y 'ojo'",
  },
  {
    seri: "ziix coii",
    spanish: "guerra",
    english: "war",
    category: "noun",
    pronunciation: "/ziːx koːi/",
    examples: ["Ziix coii quih iti", "La guerra está aquí"],
    notes: "También significa 'violación'",
  },
  {
    seri: "iizax",
    spanish: "esperanza",
    english: "hope",
    category: "noun",
    pronunciation: "/iːzax/",
    examples: ["Iizax quih iti", "La esperanza está aquí"],
    notes: "También significa 'mar', 'cabeza', 'azul' y 'bueno'",
  },
  {
    seri: "ziix",
    spanish: "miedo",
    english: "fear",
    category: "noun",
    pronunciation: "/ziːx/",
    examples: ["Ziix quih iti", "El miedo está aquí"],
    notes: "Palabra polisémica",
  },
  
  // Términos de parentesco extendidos
  {
    seri: "cmaam coos",
    spanish: "abuelo",
    english: "grandfather",
    category: "noun",
    pronunciation: "/kmaːm koːs/",
    examples: ["Cmaam coos hac", "Mi abuelo"],
  },
  {
    seri: "cmaam cmaam",
    spanish: "abuela",
    english: "grandmother",
    category: "noun",
    pronunciation: "/kmaːm kmaːm/",
    examples: ["Cmaam cmaam hac", "Mi abuela"],
  },
  {
    seri: "cöcaaj coos",
    spanish: "tío",
    english: "uncle",
    category: "noun",
    pronunciation: "/køkaːj koːs/",
    examples: ["Cöcaaj coos hac", "Mi tío"],
    notes: "También significa 'hermano'",
  },
  {
    seri: "cöcaaj cmaam",
    spanish: "tía",
    english: "aunt",
    category: "noun",
    pronunciation: "/køkaːj kmaːm/",
    examples: ["Cöcaaj cmaam hac", "Mi tía"],
    notes: "También significa 'hermana'",
  },
  {
    seri: "cöcaaj",
    spanish: "primo",
    english: "cousin",
    category: "noun",
    pronunciation: "/køkaːj/",
    examples: ["Cöcaaj hac", "Mi primo"],
    notes: "También significa 'hijo/hija'",
  },
  
  // Términos de tiempo extendidos
  {
    seri: "tooj xnoois",
    spanish: "mes",
    english: "month",
    category: "noun",
    pronunciation: "/toːj xnoːis/",
    examples: ["Tooj xnoois quih iti", "El mes está aquí"],
    notes: "También significa 'hoy' y 'semana'",
  },
  {
    seri: "tooj xnoois coi",
    spanish: "meses",
    english: "months",
    category: "noun",
    pronunciation: "/toːj xnoːis koːi/",
    examples: ["Tooj xnoois coi quih iti", "Los meses están aquí"],
  },
  {
    seri: "tooj",
    spanish: "año",
    english: "year",
    category: "noun",
    pronunciation: "/toːj/",
    examples: ["Tooj quih iti", "El año está aquí"],
    notes: "También significa 'sol', 'día', 'blanco' y 'grande'",
  },
  {
    seri: "tooj coi",
    spanish: "años",
    english: "years",
    category: "noun",
    pronunciation: "/toːj koːi/",
    examples: ["Tooj coi quih iti", "Los años están aquí"],
  },
  
  // Expresiones temporales
  {
    seri: "tooj xnoois coi",
    spanish: "ayer",
    english: "yesterday",
    category: "adverb",
    pronunciation: "/toːj xnoːis koːi/",
    examples: ["Tooj xnoois coi quih iti", "Ayer estaba aquí"],
    notes: "También significa 'semanas' y 'meses'",
  },
  {
    seri: "tooj xnoois capxöt",
    spanish: "mañana",
    english: "tomorrow",
    category: "adverb",
    pronunciation: "/toːj xnoːis kapxøt/",
    examples: ["Tooj xnoois capxöt quih iti", "Mañana estará aquí"],
  },
  {
    seri: "tooj xnoois",
    spanish: "ahora",
    english: "now",
    category: "adverb",
    pronunciation: "/toːj xnoːis/",
    examples: ["Tooj xnoois quih iti", "Ahora está aquí"],
    notes: "También significa 'hoy' y 'semana'",
  },
  {
    seri: "ziix",
    spanish: "después",
    english: "after",
    category: "adverb",
    pronunciation: "/ziːx/",
    examples: ["Ziix quih iti", "Después está aquí"],
    notes: "Palabra polisémica",
  },
  {
    seri: "quih",
    spanish: "antes",
    english: "before",
    category: "adverb",
    pronunciation: "/kih/",
    examples: ["Quih quih iti", "Antes estaba aquí"],
    notes: "También es artículo y demostrativo",
  },
];

/**
 * Verbos con Conjugaciones
 * Sistema complejo con 250+ clases de inflexión
 */
export const VERBS_WITH_CONJUGATIONS: ComcaacVerb[] = [
  {
    root: "iti",
    spanish: "estar / ser",
    english: "to be",
    verbClass: 1,
    conjugations: {
      present: {
        singular: "quih iti",
        plural: "coi iti",
      },
      past: {
        singular: "quih iti",
        plural: "coi iti",
      },
    },
    examples: ["Zo hehe quih iti", "Estoy en mi casa", "Comcaac coi iti", "Las personas están"],
    pronunciation: "/iti/",
  },
  {
    root: "ano coti",
    spanish: "pedir / necesitar",
    english: "to ask / to need",
    verbClass: 15,
    conjugations: {
      present: {
        singular: "quih ano coti",
        plural: "coi ano coti",
      },
      past: {
        singular: "quih ano coti",
        plural: "coi ano coti",
      },
    },
    examples: ["Ziix hac quih ano coti", "Yo pido", "Ziix hac quih ano coti ziix hapáctim", "Necesito un documento"],
  },
  {
    root: "xaap iti",
    spanish: "firmar",
    english: "to sign",
    verbClass: 8,
    conjugations: {
      present: {
        singular: "xaap iti",
        plural: "xaap iti coi",
      },
      past: {
        singular: "xaap iti",
        plural: "xaap iti coi",
      },
    },
    examples: ["Ziix hac xaap iti", "Yo firmo", "Cöihcaaitoj xaap iti ziix hapáctim", "El testigo firma el documento"],
  },
  {
    root: "islixp",
    spanish: "prometer",
    english: "to promise",
    verbClass: 12,
    conjugations: {
      present: {
        singular: "quih islixp",
        plural: "coi islixp",
      },
      past: {
        singular: "quih islixp",
        plural: "coi islixp",
      },
    },
    examples: ["Ziix hac quih islixp", "Yo prometo"],
  },
  {
    root: "yaza",
    spanish: "cumplir",
    english: "to fulfill",
    verbClass: 10,
    conjugations: {
      present: {
        singular: "quih yaza",
        plural: "coi yaza",
      },
      past: {
        singular: "quih yaza",
        plural: "coi yaza",
      },
    },
    examples: ["Quih yaza cöihcapxöt ziix", "Cumplir el contrato"],
  },
];

/**
 * Reglas Gramaticales Completas
 */
export const GRAMMAR_RULES: ComcaacGrammar = {
  wordOrder: {
    description: "Orden básico Sujeto + Objeto + Verbo (SOV)",
    pattern: "SOV",
    examples: [
      "Hant cöicaaj an quih ziix isoj cöicaaj zo hehe",
      "La persona que trajo el pelícano está en mi casa",
      "Cöihcaaitoj xaap iti ziix hapáctim",
      "El testigo firma el documento",
    ],
  },
  possessive: {
    firstPerson: "hac",
    secondPerson: "mapt",
    thirdPerson: "hac (contexto)",
    examples: [
      "zo hehe",
      "en mi casa",
      "hehe hac",
      "mi casa",
      "hehe mapt",
      "tu casa",
    ],
  },
  plural: {
    regular: "com",
    irregular: {
      "cmiique": "comcaac",
      "ziix": "xiica",
    },
    examples: [
      "cmiique → comcaac",
      "persona Seri → personas Seri",
      "ziix → xiica",
      "cosa → cosas",
    ],
  },
  articles: {
    singular: ["quih", "zo", "z"],
    plural: ["coi"],
    examples: [
      "quih ziix",
      "la cosa",
      "zo hehe",
      "en la casa",
      "coi comcaac",
      "las personas",
    ],
  },
  pronouns: {
    personal: {
      "yo": "hac",
      "tú": "mapt",
      "él/ella": "hac (contexto)",
      "nosotros": "hac coi",
      "ustedes": "mapt coi",
      "ellos": "hac coi",
    },
    demonstrative: {
      "este": "quih",
      "ese": "quih",
      "aquel": "quih",
    },
    interrogative: {
      "qué": "quih",
      "quién": "haxt",
      "dónde": "hant",
    },
  },
  syntax: {
    relativeClauses: "Usa 'an quih' para cláusulas relativas",
    questionFormation: "Mantiene orden SOV, entonación marca pregunta",
    negation: "No hay partícula específica de negación, se usa contexto",
    examples: [
      "Hant cöicaaj an quih ziix isoj",
      "La persona que trajo",
      "Quih ano coti?",
      "¿Qué necesitas?",
    ],
  },
};

/**
 * Función helper para buscar palabras
 */
export function findWord(seriText: string): ComcaacWord | undefined {
  const allWords = [...LEGAL_VOCABULARY, ...GENERAL_VOCABULARY];
  return allWords.find((w) => w.seri.toLowerCase() === seriText.toLowerCase());
}

/**
 * Función helper para buscar verbos
 */
export function findVerb(root: string): ComcaacVerb | undefined {
  return VERBS_WITH_CONJUGATIONS.find((v) => v.root.toLowerCase() === root.toLowerCase());
}

/**
 * Función helper para obtener vocabulario por categoría
 */
export function getWordsByCategory(category: ComcaacWord["category"]): ComcaacWord[] {
  const allWords = [...LEGAL_VOCABULARY, ...GENERAL_VOCABULARY];
  return allWords.filter((w) => w.category === category);
}

/**
 * Función helper para obtener todas las palabras (para prompts)
 */
export function getAllVocabularyText(): string {
  const allWords = [...LEGAL_VOCABULARY, ...GENERAL_VOCABULARY];
  return allWords
    .map((w) => `${w.seri} = ${w.spanish}${w.english !== w.spanish ? ` / ${w.english}` : ""}`)
    .join("\n");
}
